

/*
 *   Generated by  UI v2.00 
 *        December 25, 1993
 */


/* Module: MENU\CFG_DIR.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "dsys.h"
#include "menu.h"
static CfgP cfg;


VOID CTYP _init_EXEC(NOARG);
VOID CTYP _deinit_EXEC(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_OPEN(NOARG);


LCL ChrT MAIN_var1[64];
LCL ChrT MAIN_var2[64];
LCL ChrT MAIN_var3[64];
LCL ChrT MAIN_var4[64];
LCL ChrT MAIN_var5[64];
LCL FbldT _MAIN_Fld[]={
 {"",0,0, MAIN_var1,2,1,
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var2,4,1,
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var3,6,1,
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var4,8,1,
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var5,10,1,
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _MAIN_Frm={
 _MAIN_Fld,5,NULL,NULL,6,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _MAIN_OPEN(NOARG)
{

 Wopen(8,1,21,67,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,7,_BLUE|LGREY,'┤');
  Wmessage("Структура файловой системы",BRD_TOP,8,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,34,_BLUE|LGREY,'├');
  Wmessage("┤ ",BRD_BOT,14,_BLUE|LGREY);
  Wmessage("Ctrl+Enter",BRD_BOT,16,_BLUE|INTENSE|RED);
  Wmessage("-Запомнить",BRD_BOT,26,_BLUE|INTENSE|LGREY);
  Wmessage(", ",BRD_BOT,36,_BLUE|LGREY);
  Wmessage("Esc",BRD_BOT,38,_BLUE|INTENSE|RED);
  Wmessage("-Прервать",BRD_BOT,41,_BLUE|INTENSE|LGREY);
  Wmessage(" ├",BRD_BOT,50,_BLUE|LGREY);
  Wprts(1,2,_BLUE|INTENSE|CYAN,"Директория хранения рабочих д.систем");
  Wprts(3,2,_BLUE|INTENSE|CYAN,"Директория подключаемых д.систем");
  Wprts(5,2,_BLUE|INTENSE|CYAN,"Директория хранения результатов моделирования ");
  Wprts(7,2,_BLUE|INTENSE|CYAN,"Директория сценариев  ");
  Wprts(9,2,_BLUE|INTENSE|CYAN,"Директория временной информации ");

  _MAIN_2STR();
  EntPush();
  EntBuild(&_MAIN_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _MAIN_2STR(NOARG)
{
  strcpy(MAIN_var1,(char *)&cfg->dir_work); strsetsz(MAIN_var1,63);
  strcpy(MAIN_var2,(char *)&cfg->dir_include); strsetsz(MAIN_var2,63);
  strcpy(MAIN_var3,(char *)&cfg->dir_result); strsetsz(MAIN_var3,63);
  strcpy(MAIN_var4,(char *)&cfg->dir_project); strsetsz(MAIN_var4,63);
  strcpy(MAIN_var5,(char *)&cfg->dir_tmp); strsetsz(MAIN_var5,63);
 return;
}
LCL VOID CTYP _MAIN_2VAL(NOARG)
{
    strcpy((char *)&cfg->dir_work,MAIN_var1);
    strcpy((char *)&cfg->dir_include,MAIN_var2);
    strcpy((char *)&cfg->dir_result,MAIN_var3);
    strcpy((char *)&cfg->dir_project,MAIN_var4);
    strcpy((char *)&cfg->dir_tmp,MAIN_var5);
 return;
}

LCL VOID CTYP _init_EXEC(NOARG)
{
cfg=EdtGetCfg();   
  return;
}
LCL VOID CTYP _deinit_EXEC(NOARG)
{
 EdtCheckCfg();           
                          
  return;
}
VOID CTYP CFG_DIR(NOARG)
{
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _init_EXEC();
 _MAIN_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _MAIN_2STR();
 EntPush();
 EntBuild(&_MAIN_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_MAIN_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _MAIN_2VAL();
    EntResult=1;
    }
  _deinit_EXEC();
}
  return;
}

/*** END OF FILE ***/
