

/*
 *   Generated by  UI v2.00 
 *        December 2, 1993
 */


/* Module: MENU\CFG_MOD.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "dsys.h"
#include "help.h"
#include "menu.h"
WModeT _wmode;
MModeT _msg;  EModeT _emode;
static CfgP cfg;
int emode[3]={0,1,0};
int wmode[3]={0,1,0};
int msg[2]={1,0};
int mtime=60,mfreemem=0;
#define Execute Perform
int clear_all()
{
 int i;

 for(i=0;i<3;i++)
    {
    emode[i]=0;
    wmode[i]=0;
    }
 for(i=0;i<2;i++) msg[i]=0;
 return 0;
 }

VOID CTYP _ini_EXEC(NOARG);
VOID CTYP _deinit_EXEC(NOARG);
VOID CTYP _GetCompiler_ENTRY(NOARG);
VOID CTYP _GetExecuter_ENTRY(NOARG);
VOID CTYP _emode_MENU(NOARG);
VOID CTYP _wmode_MENU(NOARG);
VOID CTYP _msg_MENU(NOARG);
VOID CTYP _ini_compil_EXEC(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _set_compil_EXEC(NOARG);
VOID CTYP _emode_MENU(NOARG);
VOID CTYP _wmode_MENU(NOARG);
VOID CTYP _msg_MENU(NOARG);
VOID CTYP _ini_exec_EXEC(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _set_exec_EXEC(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _params_WRITE(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);
VOID CTYP _GetCompiler_2STR(NOARG);
VOID CTYP _GetCompiler_OPEN(NOARG);
VOID CTYP _GetExecuter_2STR(NOARG);
VOID CTYP _GetExecuter_OPEN(NOARG);
VOID CTYP _emode_2STR(NOARG);
VOID CTYP _emode_MSG(NOARG);
VOID CTYP _wmode_2STR(NOARG);
VOID CTYP _wmode_MSG(NOARG);
VOID CTYP _msg_2STR(NOARG);
VOID CTYP _msg_MSG(NOARG);
VOID CTYP _params_2STR(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
InitEasyGenParam();
MOD_TEST();
StoreEasyGenParam();
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
MOD_GLB();
return;
}

LCL IbldT _MAIN_Itm[]={
{" Тестовых вх. сигналов   ",'',ITM_NOR|ITM_BEF,0,0,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{" Параметры моделирования ",'',ITM_NOR|ITM_BEF,1,0,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{" Редактирование          ",'',ITM_NOR|ITM_NSL,3,0,  5,HLP_NONE,
   0,6,NULL,NULL,NULL,
   "",NULL},
{" Сценарий по умолчанию   ",'',ITM_NOR|ITM_NSL,4,0,  7,HLP_NONE,
   0,8,NULL,NULL,NULL,
   "",NULL},
{" Компилятор д.систем     ",'',ITM_NOR,6,0,  9,HLP_NONE,
   0,10,NULL,_GetCompiler_ENTRY,NULL,
   "",NULL},
{" Моделирование д.систем  ",'',ITM_NOR,7,0,  11,HLP_NONE,
   0,12,NULL,_GetExecuter_ENTRY,NULL,
   "",NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,6,5,33,14,59,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_MAIN_MSG,13, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("Параметры",BRD_TOP,4,_BLUE|LGREY);
  Wbprintc(BRD_LFT,3,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_LFT,6,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_RGT,3,_BLUE|INTENSE|LGREY,'┤');
  Wbprintc(BRD_RGT,6,_BLUE|INTENSE|LGREY,'┤');
  Wprts(2,0,_BLUE|INTENSE|LGREY,"───");
  Wprts(2,3,_BLUE|LGREY,"Сценарии");
  Wprts(2,11,_BLUE|INTENSE|LGREY,"──────────────");
  Wprts(5,0,_BLUE|INTENSE|LGREY,"───");
  Wprts(5,3,_BLUE|LGREY,"Вычисления");
  Wprts(5,13,_BLUE|INTENSE|LGREY,"────────────");
  {
  MnuDsp(&_MAIN_Mnu);
  }
  return;
}
LCL VOID CTYP _ini_EXEC(NOARG)
{
cfg=EdtGetCfg();                    
  return;
}
LCL VOID CTYP _deinit_EXEC(NOARG)
{
EdtCheckCfg();                      
  return;
}

LCL ChrT GetCompiler_var1[71];
LCL ChrT GetCompiler_var13[5];
LCL FbldT _GetCompiler_Fld[]={
 {"",0,0, GetCompiler_var1,1,1,
  "**********************************************************************",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, GetCompiler_var13,8,59,
  "9999",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _GetCompiler_Frm={
 _GetCompiler_Fld,2,NULL,NULL,16,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _GetCompiler_OPEN(NOARG)
{

 Wopen(10,2,20,76,BOX_VER,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 CurHide();
  Wbprintc(BRD_TOP,8,_BLUE|INTENSE|LGREY,'┤');
  Wmessage("Компиляция",BRD_TOP,9,_BLUE|LGREY);
  Wbprintc(BRD_TOP,19,_BLUE|INTENSE|LGREY,'├');
  Wmessage("▓▓▓▓",BRD_BOT,1,_BLUE|INTENSE|LGREY);
  Wmessage("F2",BRD_BOT,5,_BLUE|INTENSE|RED);
  Wmessage("-Выполнение",BRD_BOT,7,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,18,_BLUE|INTENSE|LGREY);
  Wmessage("F3",BRD_BOT,20,_BLUE|INTENSE|RED);
  Wmessage("-Задержка",BRD_BOT,22,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,31,_BLUE|INTENSE|LGREY);
  Wmessage("F4",BRD_BOT,33,_BLUE|INTENSE|RED);
  Wmessage("-Сообщения",BRD_BOT,35,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,45,_BLUE|INTENSE|LGREY);
  Wmessage("Ent",BRD_BOT,47,_BLUE|INTENSE|RED);
  Wmessage("-Запись",BRD_BOT,50,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,57,_BLUE|INTENSE|LGREY);
  Wmessage("Esc",BRD_BOT,59,_BLUE|INTENSE|RED);
  Wmessage("-Прервать",BRD_BOT,62,_BLUE|LGREY);
  Wmessage("▓▓▓",BRD_BOT,71,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_LFT,3,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_RGT,3,_BLUE|INTENSE|LGREY,'╢');
  Wprts(0,3,_BLUE|INTENSE|LGREY,"Строка");
  Wprts(0,10,_BLUE|INTENSE|LGREY,"вызова");
  Wprts(0,17,_BLUE|INTENSE|LGREY,"компилятора");
  Wprts(0,29,_BLUE|INTENSE|LGREY,"экрана");
  Wprts(0,36,_BLUE|INTENSE|LGREY,"в");
  Wprts(0,38,_BLUE|INTENSE|LGREY,"д.систему");
  Wprts(2,0,_BLUE|INTENSE|LGREY,"─────────────────────────────────────────────────────────────────────────");
  Wprts(4,8,_BLUE|LGREY," ");
  Wprts(4,29,_BLUE|LGREY," ");
  Wprts(4,50,_BLUE|LGREY," ");
  Wprts(5,8,_BLUE|LGREY," ");
  Wprts(5,29,_BLUE|LGREY," ");
  Wprts(5,50,_BLUE|LGREY," ");
  Wprts(6,8,_BLUE|LGREY," ");
  Wprts(6,29,_BLUE|LGREY," ");
  Wprts(6,38,_BLUE|LGREY,"    ");
  Wprts(8,3,_BLUE|INTENSE|LGREY,"Обьем");
  Wprts(8,9,_BLUE|INTENSE|LGREY,"свободной");
  Wprts(8,19,_BLUE|INTENSE|LGREY,"памяти,");
  Wprts(8,27,_BLUE|INTENSE|LGREY,"необходимой");
  Wprts(8,39,_BLUE|INTENSE|LGREY,"для");
  Wprts(8,43,_BLUE|INTENSE|LGREY,"работы");
  Wprts(8,50,_BLUE|INTENSE|LGREY,"(0=вся):");
  Wprts(8,64,_BLUE|INTENSE|LGREY,"Kb");

  _GetCompiler_2STR();
  EntPush();
  EntBuild(&_GetCompiler_Frm);
  EntDsp();
  EntFree();
  EntPop();

  _params_WRITE();
  return;
}
LCL VOID CTYP _GetCompiler_2STR(NOARG)
{
  strcpy(GetCompiler_var1,(char *)&cfg->Compile.cmd); strsetsz(GetCompiler_var1,70);
  cvtic(GetCompiler_var13,mfreemem,4);
 return;
}
LCL VOID CTYP _GetCompiler_2VAL(NOARG)
{
    strcpy((char *)&cfg->Compile.cmd,GetCompiler_var1);
    mfreemem=cvtci(GetCompiler_var13);
 return;
}

LCL VOID CTYP _GetCompiler_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _ini_compil_EXEC();
 _GetCompiler_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 KbndSet(Key_F2,_emode_MENU,0);
 KbndSet(Key_F3,_wmode_MENU,0);
 KbndSet(Key_F4,_msg_MENU,0);
 _GetCompiler_2STR();
 EntPush();
 EntBuild(&_GetCompiler_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_GetCompiler_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndClr(Key_F2);
 KbndClr(Key_F3);
 KbndClr(Key_F4);
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _GetCompiler_2VAL();
    EntResult=1;
    }
  _set_compil_EXEC();
}

LCL ChrT GetExecuter_var2[71];
LCL ChrT GetExecuter_var12[5];
LCL FbldT _GetExecuter_Fld[]={
 {"",0,0, GetExecuter_var2,1,1,
  "**********************************************************************",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, GetExecuter_var12,8,59,
  "9999",NULL,NULL,NULL,
  0,18,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _GetExecuter_Frm={
 _GetExecuter_Fld,2,NULL,NULL,19,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _GetExecuter_OPEN(NOARG)
{

 Wopen(10,2,20,76,BOX_VER,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,8,_BLUE|INTENSE|LGREY,'┤');
  Wmessage("Моделирование",BRD_TOP,9,_BLUE|LGREY);
  Wbprintc(BRD_TOP,22,_BLUE|INTENSE|LGREY,'├');
  Wmessage("▓▓▓▓",BRD_BOT,1,_BLUE|INTENSE|LGREY);
  Wmessage("F2",BRD_BOT,5,_BLUE|INTENSE|RED);
  Wmessage("-Выполнение",BRD_BOT,7,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,18,_BLUE|INTENSE|LGREY);
  Wmessage("F3",BRD_BOT,20,_BLUE|INTENSE|RED);
  Wmessage("-Задержка",BRD_BOT,22,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,31,_BLUE|INTENSE|LGREY);
  Wmessage("F4",BRD_BOT,33,_BLUE|INTENSE|RED);
  Wmessage("-Сообщения",BRD_BOT,35,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,45,_BLUE|INTENSE|LGREY);
  Wmessage("Ent",BRD_BOT,47,_BLUE|INTENSE|RED);
  Wmessage("-Запись",BRD_BOT,50,_BLUE|LGREY);
  Wmessage("▓▓",BRD_BOT,57,_BLUE|INTENSE|LGREY);
  Wmessage("Esc",BRD_BOT,59,_BLUE|INTENSE|RED);
  Wmessage("-Прервать",BRD_BOT,62,_BLUE|LGREY);
  Wmessage("▓▓▓",BRD_BOT,71,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_LFT,3,_BLUE|INTENSE|LGREY,'╟');
  Wbprintc(BRD_RGT,3,_BLUE|INTENSE|LGREY,'╢');
  Wprts(0,3,_BLUE|INTENSE|LGREY,"Строка");
  Wprts(0,10,_BLUE|INTENSE|LGREY,"вызова");
  Wprts(0,17,_BLUE|INTENSE|LGREY,"программы");
  Wprts(0,27,_BLUE|INTENSE|LGREY,"моделирования");
  Wprts(0,41,_BLUE|INTENSE|LGREY,"д.системы");
  Wprts(2,0,_BLUE|INTENSE|LGREY,"─────────────────────────────────────────────────────────────────────────");
  Wprts(4,8,_BLUE|LGREY," ");
  Wprts(4,29,_BLUE|LGREY," ");
  Wprts(4,50,_BLUE|LGREY," ");
  Wprts(5,8,_BLUE|LGREY," ");
  Wprts(5,29,_BLUE|LGREY," ");
  Wprts(5,50,_BLUE|LGREY," ");
  Wprts(6,8,_BLUE|LGREY," ");
  Wprts(6,29,_BLUE|LGREY," ");
  Wprts(6,38,_BLUE|LGREY,"    ");
  Wprts(8,3,_BLUE|INTENSE|LGREY,"Обьем");
  Wprts(8,9,_BLUE|INTENSE|LGREY,"свободной");
  Wprts(8,19,_BLUE|INTENSE|LGREY,"памяти,");
  Wprts(8,27,_BLUE|INTENSE|LGREY,"необходимой");
  Wprts(8,39,_BLUE|INTENSE|LGREY,"для");
  Wprts(8,43,_BLUE|INTENSE|LGREY,"работы");
  Wprts(8,50,_BLUE|INTENSE|LGREY,"(0=вся):");
  Wprts(8,64,_BLUE|INTENSE|LGREY,"Kb");

  _GetExecuter_2STR();
  EntPush();
  EntBuild(&_GetExecuter_Frm);
  EntDsp();
  EntFree();
  EntPop();

  _params_WRITE();
  return;
}
LCL VOID CTYP _GetExecuter_2STR(NOARG)
{
  strcpy(GetExecuter_var2,(char *)&cfg->Perform.cmd); strsetsz(GetExecuter_var2,70);
  cvtic(GetExecuter_var12,mfreemem,4);
 return;
}
LCL VOID CTYP _GetExecuter_2VAL(NOARG)
{
    strcpy((char *)&cfg->Perform.cmd,GetExecuter_var2);
    mfreemem=cvtci(GetExecuter_var12);
 return;
}

LCL VOID CTYP _GetExecuter_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _ini_exec_EXEC();
 _GetExecuter_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 KbndSet(Key_F2,_emode_MENU,0);
 KbndSet(Key_F3,_wmode_MENU,0);
 KbndSet(Key_F4,_msg_MENU,0);
 _GetExecuter_2STR();
 EntPush();
 EntBuild(&_GetExecuter_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_GetExecuter_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndClr(Key_F2);
 KbndClr(Key_F3);
 KbndClr(Key_F4);
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _GetExecuter_2VAL();
    EntResult=1;
    }
  _set_exec_EXEC();
}

LCL VOID CTYP _opt7_ACT(NOARG)
{
emode[0]=1;
emode[1]=0;
emode[2]=0;
_emode=inWINDOW;
_params_WRITE();
return;
}

LCL VOID CTYP _opt10_ACT(NOARG)
{
emode[0]=0;
emode[1]=1;
emode[2]=0;
_emode=inSCREEN;
_params_WRITE();
return;
}

LCL VOID CTYP _opt13_ACT(NOARG)
{
emode[0]=0;
emode[1]=0;
emode[2]=1;
_emode=HIDDEN;
_params_WRITE();
return;
}

LCL IbldT _emode_Itm[]={
{"      в окне       ",'',ITM_NOR|ITM_BEF,0,0,  20,HLP_NONE,
   0,21,NULL,_opt7_ACT,NULL,
   "",NULL},
{"   на экране DOS   ",'',ITM_NOR|ITM_BEF,1,0,  22,HLP_NONE,
   0,23,NULL,_opt10_ACT,NULL,
   "",NULL},
{"     невидимое     ",'',ITM_NOR|ITM_BEF,2,0,  24,HLP_NONE,
   0,25,NULL,_opt13_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _emode_MSG(NOARG);
LCL MbldT _emode_Mnu={
   _emode_Itm,3,14,7,18,27,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_HOR,
   _CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,
   _CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,_BLUE|INTENSE|CYAN,
   0,_emode_MSG,26, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _emode_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,4,_CYAN|INTENSE|CYAN,'╡');
  Wmessage("Выполнение",BRD_TOP,5,_CYAN|BLACK);
  Wbprintc(BRD_TOP,15,_CYAN|INTENSE|CYAN,'╞');
  Wmessage("Ent",BRD_BOT,1,_CYAN|RED);
  Wmessage("-выбор",BRD_BOT,4,_CYAN|INTENSE|BLACK);
  Wbprintc(BRD_BOT,10,_CYAN|INTENSE|CYAN,',');
  Wmessage("Esc",BRD_BOT,11,_CYAN|RED);
  Wmessage("-сброс",BRD_BOT,14,_CYAN|INTENSE|BLACK);
  {
  MnuDsp(&_emode_Mnu);
  }
  return;
}
LCL VOID CTYP _emode_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_emode_Mnu)=IbldTag(&_emode_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_emode_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt8_ACT(NOARG)
{
wmode[0]=1;
wmode[1]=0;
wmode[2]=0;
_wmode=NOWAIT_KEY;
_params_WRITE();
return;
}

LCL VOID CTYP _opt11_ACT(NOARG)
{
wmode[0]=0;
wmode[1]=1;
wmode[2]=0;
_wmode=WAIT_KEY;
_params_WRITE();
return;
}

LCL VOID CTYP _opt14_ACT(NOARG)
{
wmode[0]=0;
wmode[1]=0;
wmode[2]=1;
_wmode=WAIT_TIME;
_params_WRITE();
return;
}

LCL IbldT _wmode_Itm[]={
{"    без задержки    ",'',ITM_NOR|ITM_BEF,0,0,  27,HLP_NONE,
   0,28,NULL,_opt8_ACT,NULL,
   "",NULL},
{" до нажатия клавиши ",'',ITM_NOR|ITM_BEF,1,0,  29,HLP_NONE,
   0,30,NULL,_opt11_ACT,NULL,
   "",NULL},
{"    ждать время     ",'',ITM_NOR|ITM_BEF,2,0,  31,HLP_NONE,
   0,32,NULL,_opt14_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _wmode_MSG(NOARG);
LCL MbldT _wmode_Mnu={
   _wmode_Itm,3,14,28,18,49,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_HOR,
   _CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,
   _CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,_BLUE|INTENSE|CYAN,
   0,_wmode_MSG,33, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _wmode_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,6,_CYAN|INTENSE|CYAN,'╡');
  Wmessage("Задержка",BRD_TOP,7,_CYAN|BLACK);
  Wbprintc(BRD_TOP,15,_CYAN|INTENSE|CYAN,'╞');
  Wmessage("Ent",BRD_BOT,1,_CYAN|RED);
  Wmessage("-выбор",BRD_BOT,4,_CYAN|INTENSE|BLACK);
  Wbprintc(BRD_BOT,10,_CYAN|INTENSE|CYAN,',');
  Wmessage("Esc",BRD_BOT,11,_CYAN|RED);
  Wmessage("-сброс",BRD_BOT,14,_CYAN|INTENSE|BLACK);
  {
  MnuDsp(&_wmode_Mnu);
  }
  return;
}
LCL VOID CTYP _wmode_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_wmode_Mnu)=IbldTag(&_wmode_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_wmode_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt9_ACT(NOARG)
{
msg[0]=1;
msg[1]=0;
_msg=SAVE_MSG;
_params_WRITE();
return;
}

LCL VOID CTYP _opt12_ACT(NOARG)
{
msg[0]=0;
msg[1]=1;
_msg=NOSAVE_MSG;
_params_WRITE();
return;
}

LCL IbldT _msg_Itm[]={
{"   Сохранять   ",'',ITM_NOR|ITM_BEF,0,0,  34,HLP_NONE,
   0,35,NULL,_opt9_ACT,NULL,
   "",NULL},
{"  Не сохранять ",'',ITM_NOR|ITM_BEF,1,0,  36,HLP_NONE,
   0,37,NULL,_opt12_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _msg_MSG(NOARG);
LCL MbldT _msg_Mnu={
   _msg_Itm,2,14,51,17,67,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_HOR,
   _CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,
   _CYAN|INTENSE|CYAN,_CYAN|INTENSE|CYAN,_BLUE|INTENSE|CYAN,
   0,_msg_MSG,38, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _msg_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,3,_CYAN|INTENSE|CYAN,'╡');
  Wmessage("Сообщения",BRD_TOP,4,_CYAN|BLACK);
  Wbprintc(BRD_TOP,13,_CYAN|INTENSE|CYAN,'╞');
  Wmessage("Ent",BRD_BOT,1,_CYAN|RED);
  Wmessage("-выбор",BRD_BOT,4,_CYAN|INTENSE|BLACK);
  Wbprintc(BRD_BOT,10,_CYAN|INTENSE|CYAN,',');
  Wmessage("Esc",BRD_BOT,11,_CYAN|RED);
  Wbprintc(BRD_BOT,14,_CYAN|INTENSE|BLACK,'-');
  {
  MnuDsp(&_msg_Mnu);
  }
  return;
}
LCL VOID CTYP _msg_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_msg_Mnu)=IbldTag(&_msg_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_msg_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
LCL VOID CTYP _ini_compil_EXEC(NOARG)
{
clear_all();                              
                                          
switch(_emode=cfg->Compile.win)           
  {                                       
  case inWINDOW:  emode[0]=1;break;       
  case inSCREEN:  emode[1]=1;break;       
  case HIDDEN:    emode[2]=1;break;       
  }                                       
switch(_wmode=cfg->Compile.wait)          
  {                                       
  case NOWAIT_KEY:wmode[0]=1;break;       
  case WAIT_KEY:  wmode[1]=1;break;       
  case WAIT_TIME: wmode[2]=1;break;       
  }                                       
switch(_msg=cfg->Compile.msg)             
  {                                       
  case SAVE_MSG:  msg[0]=1;break;         
  case NOSAVE_MSG:msg[1]=1;break;         
  }                                       
mtime=cfg->Compile.wtime;                 
mfreemem=cfg->Compile.FreeMem;            
  return;
}

LCL ChrT params_var3[2];
LCL ChrT params_var4[2];
LCL ChrT params_var5[2];
LCL ChrT params_var6[2];
LCL ChrT params_var7[2];
LCL ChrT params_var8[2];
LCL ChrT params_var9[2];
LCL ChrT params_var10[2];
LCL ChrT params_var11[6];
LCL FbldT _params_Fld[]={
 {"",0,0, params_var3,1,5,
  "Y",NULL,NULL,NULL,
  0,39,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var4,1,26,
  "Y",NULL,NULL,NULL,
  0,40,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var5,1,47,
  "Y",NULL,NULL,NULL,
  0,41,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var6,2,5,
  "Y",NULL,NULL,NULL,
  0,42,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var7,2,26,
  "Y",NULL,NULL,NULL,
  0,43,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var8,2,47,
  "Y",NULL,NULL,NULL,
  0,44,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var9,3,5,
  "Y",NULL,NULL,NULL,
  0,45,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var10,3,26,
  "Y",NULL,NULL,NULL,
  0,46,HLP_NONE,
  FLD_NUL,0,FLD_CHG},
 {"",0,0, params_var11,3,35,
  "99999",NULL,NULL,NULL,
  0,47,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _params_Frm={
 _params_Fld,9,NULL,NULL,48,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _params_2STR(NOARG)
{
 strcpy(params_var3,(emode[0] != 0 ? "Y" : "N"));
 strcpy(params_var4,(wmode[0] != 0 ? "Y" : "N"));
 strcpy(params_var5,(msg[0] != 0 ? "Y" : "N"));
 strcpy(params_var6,(emode[1] != 0 ? "Y" : "N"));
 strcpy(params_var7,(wmode[1] != 0 ? "Y" : "N"));
 strcpy(params_var8,(msg[1] != 0 ? "Y" : "N"));
 strcpy(params_var9,(emode[2] != 0 ? "Y" : "N"));
 strcpy(params_var10,(wmode[2] != 0 ? "Y" : "N"));
  cvtic(params_var11,mtime,5);
 return;
}
LCL VOID CTYP _params_WRITE(NOARG)
{
 Wopen(14,6,17,69,BOX_SPA,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 CurHide();
  Wprts(0,3,_BLUE|INTENSE|LGREY,"Выполнение:");
  Wprts(0,24,_BLUE|INTENSE|LGREY,"Задержка:");
  Wprts(0,45,_BLUE|INTENSE|LGREY,"Сообщения:");
  Wprts(1,3,_BLUE|LGREY," (");
  Wprts(1,6,_BLUE|LGREY,") в окне           (");
  Wprts(1,27,_BLUE|LGREY,") нет              (");
  Wprts(1,48,_BLUE|LGREY,") сохранять    ");
  Wprts(2,3,_BLUE|LGREY," (");
  Wprts(2,6,_BLUE|LGREY,") на экране DOS    (");
  Wprts(2,27,_BLUE|LGREY,") по клавише       (");
  Wprts(2,48,_BLUE|LGREY,") не сохранять ");
  Wprts(3,3,_BLUE|LGREY," (");
  Wprts(3,6,_BLUE|LGREY,") невидимое        (");
  Wprts(3,27,_BLUE|LGREY,") ждать ");
  Wprts(3,41,_BLUE|LGREY,"сек ");

  _params_2STR();
  EntPush();
  EntBuild(&_params_Frm);
  EntDsp();
  EntFree();
  EntPop();

 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _set_compil_EXEC(NOARG)
{
if(EntResult) {                     
  cfg->Compile.wtime=mtime;         
  cfg->Compile.FreeMem=mfreemem;    
  cfg->Compile.wait=_wmode;         
  cfg->Compile.msg=_msg;            
  cfg->Compile.win=_emode;          
  }                                 
  return;
}
LCL VOID CTYP _ini_exec_EXEC(NOARG)
{
clear_all();                              
                                          
switch(_emode=cfg->Execute.win)           
  {                                       
  case inWINDOW:  emode[0]=1;break;       
  case inSCREEN:  emode[1]=1;break;       
  case HIDDEN:    emode[2]=1;break;       
  }                                       
switch(_wmode=cfg->Execute.wait)          
  {                                       
  case NOWAIT_KEY:wmode[0]=1;break;       
  case WAIT_KEY:  wmode[1]=1;break;       
  case WAIT_TIME: wmode[2]=1;break;       
  }                                       
switch(_msg=cfg->Execute.msg)             
  {                                       
  case SAVE_MSG:  msg[0]=1;break;         
  case NOSAVE_MSG:msg[1]=1;break;         
  }                                       
mtime=cfg->Execute.wtime;                 
mfreemem=cfg->Execute.FreeMem;            
  return;
}
LCL VOID CTYP _set_exec_EXEC(NOARG)
{
if(EntResult) {                     
  cfg->Execute.wtime=mtime;         
  cfg->Execute.FreeMem=mfreemem;    
  cfg->Execute.wait=_wmode;         
  cfg->Execute.msg=_msg;            
  cfg->Execute.win=_emode;          
  }                                 
  return;
}
VOID CTYP CFG_MOD(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[0]);
  _ini_EXEC();
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_MAIN_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
  _deinit_EXEC();
}
  return;
}

/*** END OF FILE ***/
