

/*
 *   Generated by  UI v2.00 
 *        December 2, 1993
 */


/* Module: MENU\CFG_RES.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "menu.h"
#include "dsys.h"

static CfgP cfg;



VOID CTYP _init_EXEC(NOARG);
VOID CTYP _deinit_EXEC(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_OPEN(NOARG);


LCL ChrT MAIN_var1[65];
LCL ChrT MAIN_var2[6];
LCL FbldT _MAIN_Fld[]={
 {"",0,0, MAIN_var1,1,1,
  "****************************************************************",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var2,3,23,
  "99999",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _MAIN_Frm={
 _MAIN_Fld,2,NULL,NULL,3,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _MAIN_OPEN(NOARG)
{

 Wopen(8,9,13,76,BOX_SNG,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Архив├",BRD_TOP,11,_BLUE|INTENSE|LGREY);
  Wmessage("┤ ",BRD_BOT,18,_BLUE|INTENSE|LGREY);
  Wmessage("Ent",BRD_BOT,20,_BLUE|INTENSE|MAGENTA);
  Wmessage("-Запомнить",BRD_BOT,23,_BLUE|LGREY);
  Wmessage(", ",BRD_BOT,33,_BLUE|INTENSE|LGREY);
  Wmessage("Esc",BRD_BOT,35,_BLUE|INTENSE|MAGENTA);
  Wmessage("-Прервать",BRD_BOT,38,_BLUE|LGREY);
  Wmessage(" ├",BRD_BOT,47,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_LFT,3,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_RGT,3,_BLUE|INTENSE|LGREY,'┤');
  Wprts(0,2,_BLUE|INTENSE|LGREY,"Программа");
  Wprts(0,12,_BLUE|INTENSE|LGREY,"ведения");
  Wprts(0,20,_BLUE|INTENSE|LGREY,"архива:");
  Wprts(2,0,_BLUE|INTENSE|LGREY,"──────────────────────────────────────────────────────────────────");
  Wprts(3,2,_BLUE|INTENSE|LGREY,"Необходимая");
  Wprts(3,14,_BLUE|INTENSE|LGREY,"память:");
  Wprts(3,29,_BLUE|INTENSE|LGREY,"Kb");

  _MAIN_2STR();
  EntPush();
  EntBuild(&_MAIN_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _MAIN_2STR(NOARG)
{
  strcpy(MAIN_var1,(char *)&cfg->Archive.cmd); strsetsz(MAIN_var1,64);
  cvtic(MAIN_var2,cfg->Archive.FreeMem,5);
 return;
}
LCL VOID CTYP _MAIN_2VAL(NOARG)
{
    strcpy((char *)&cfg->Archive.cmd,MAIN_var1);
    cfg->Archive.FreeMem=cvtci(MAIN_var2);
 return;
}

LCL VOID CTYP _init_EXEC(NOARG)
{
cfg=EdtGetCfg();                  
                                  
                                  
                                  
                                  
  return;
}
LCL VOID CTYP _deinit_EXEC(NOARG)
{
 EdtCheckCfg();        
  return;
}
VOID CTYP CFG_RES(NOARG)
{
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _init_EXEC();
 _MAIN_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _MAIN_2STR();
 EntPush();
 EntBuild(&_MAIN_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_MAIN_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _MAIN_2VAL();
    EntResult=1;
    }
  _deinit_EXEC();
}
  return;
}

/*** END OF FILE ***/
