

/*
 *   Generated by  UI v2.00 
 *        May 11, 1993
 */


/* Module: MENU\EDT_POIN.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
#include "dsys.h"
#include "menu.h"



VOID CTYP _Add_WRITE(NOARG);
VOID CTYP _Mul_WRITE(NOARG);
VOID CTYP _Sub_WRITE(NOARG);
VOID CTYP _Div_WRITE(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);
VOID CTYP _Add_2STR(NOARG);
VOID CTYP _Mul_2STR(NOARG);
VOID CTYP _Sub_2STR(NOARG);
VOID CTYP _Div_2STR(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
EdtPutBlock(BLK_ADD);
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
EdtPutBlock(BLK_MUL);
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
EdtPutBlock(BLK_SUB);
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
EdtPutBlock(BLK_DIV);
return;
}

LCL IbldT _MAIN_Itm[]={
{"    Сумма    ",'',ITM_NOR|ITM_BEF,1,6,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{" Произведение",'',ITM_NOR|ITM_BEF,1,22,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{"   Разность  ",'',ITM_NOR|ITM_BEF,7,6,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   "",NULL},
{"   Частное   ",'',ITM_NOR|ITM_BEF,7,22,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,4,7,18,21,60,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_DBL,
   _BLUE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_MAIN_MSG,9, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,6,_BLUE|LGREY,'╡');
  Wmessage("Арифметические узлы д.системы",BRD_TOP,7,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,36,_BLUE|LGREY,'╞');
  Wprts(2,10,_BLUE|LGREY,"Alt-A");
  Wprts(2,26,_BLUE|LGREY,"Alt-M ");
  Wprts(8,10,_BLUE|LGREY,"Alt-S ");
  Wprts(8,26,_BLUE|LGREY,"Alt-D ");
  {
  extern MbldT _MAIN_Mnu;
  MnuDsp(&_MAIN_Mnu);
  }
{
 extern struct _WDEF WDEF_Add;

struct _WDEF _WDEF_Add=
    {28,11,34,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Add,&_WDEF_Add,sizeof(WDEF_Add));
}
  _Add_WRITE();
{
 extern struct _WDEF WDEF_Mul;

struct _WDEF _WDEF_Mul=
    {44,11,50,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Mul,&_WDEF_Mul,sizeof(WDEF_Mul));
}
  _Mul_WRITE();
{
 extern struct _WDEF WDEF_Sub;

struct _WDEF _WDEF_Sub=
    {28,17,34,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Sub,&_WDEF_Sub,sizeof(WDEF_Sub));
}
  _Sub_WRITE();
{
 extern struct _WDEF WDEF_Div;

struct _WDEF _WDEF_Div=
    {44,17,50,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Div,&_WDEF_Div,sizeof(WDEF_Div));
}
  _Div_WRITE();
  return;
}
LCL VOID CTYP _Add_2STR(NOARG)
{
 return;
}

struct _WDEF WDEF_Add=
    {28,11,34,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Add_WRITE(NOARG)
{
 Wopen(WDEF_Add.BegR,WDEF_Add.BegC,
       WDEF_Add.EndR,WDEF_Add.EndC,
       WDEF_Add.FrmT,WDEF_Add.FrmA,WDEF_Add.Dat);
 if(WDEF_Add.Shadow) Wshadow(WDEF_Add.Sat);
 CurHide();
  Wprts(1,0,_CYAN|INTENSE|CYAN,"──┤+├──");
  Wprts(2,3,_CYAN|INTENSE|CYAN,"\030" "");
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _Mul_2STR(NOARG)
{
 return;
}

struct _WDEF WDEF_Mul=
    {44,11,50,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Mul_WRITE(NOARG)
{
 Wopen(WDEF_Mul.BegR,WDEF_Mul.BegC,
       WDEF_Mul.EndR,WDEF_Mul.EndC,
       WDEF_Mul.FrmT,WDEF_Mul.FrmA,WDEF_Mul.Dat);
 if(WDEF_Mul.Shadow) Wshadow(WDEF_Mul.Sat);
 CurHide();
  Wprts(1,0,_CYAN|INTENSE|CYAN,"──┤*├──");
  Wprts(2,3,_CYAN|INTENSE|CYAN,"\030" "");
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _Sub_2STR(NOARG)
{
 return;
}

struct _WDEF WDEF_Sub=
    {28,17,34,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Sub_WRITE(NOARG)
{
 Wopen(WDEF_Sub.BegR,WDEF_Sub.BegC,
       WDEF_Sub.EndR,WDEF_Sub.EndC,
       WDEF_Sub.FrmT,WDEF_Sub.FrmA,WDEF_Sub.Dat);
 if(WDEF_Sub.Shadow) Wshadow(WDEF_Sub.Sat);
 CurHide();
  Wprts(1,0,_CYAN|INTENSE|CYAN,"──┤-├──");
  Wprts(2,3,_CYAN|INTENSE|CYAN,"\030" "");
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _Div_2STR(NOARG)
{
 return;
}

struct _WDEF WDEF_Div=
    {44,17,50,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Div_WRITE(NOARG)
{
 Wopen(WDEF_Div.BegR,WDEF_Div.BegC,
       WDEF_Div.EndR,WDEF_Div.EndC,
       WDEF_Div.FrmT,WDEF_Div.FrmA,WDEF_Div.Dat);
 if(WDEF_Div.Shadow) Wshadow(WDEF_Div.Sat);
 CurHide();
  Wprts(1,0,_CYAN|INTENSE|CYAN,"──┤/├──");
  Wprts(2,3,_CYAN|INTENSE|CYAN,"\030" "");
 Wunlink(Whandle());
 return;
}
VOID CTYP EDT_POIN(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 tcxl_old_kb=KbndChg(tcxl_kb);

 MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[0]);
 MnuBuild(&_MAIN_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
