

/*
 *   Generated by  UI v2.00 
 *        May 11, 1993
 */


/* Module: MENU\EDT_INFO.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
#include "tcxlvid.h"
#include "tcxlhdw.h"

char DispType[10]="VGA",KeybType[15]="Mouse",Status[15]="None";
int AllMem=640,UseMem=0,FreeMem=0;

VOID CTYP _MAIN_2STR(NOARG);

LCL ChrT  CurName[14]="NONAME.DSF";
LCL IntT   UseSys=0;
LCL IntT   UseGen=0;

LCL ChrT MAIN_var1[8];
LCL ChrT MAIN_var2[8];
LCL ChrT MAIN_var3[8];
LCL ChrT MAIN_var4[11];
LCL ChrT MAIN_var5[14];
LCL ChrT MAIN_var6[14];
LCL ChrT MAIN_var7[5];
LCL ChrT MAIN_var8[5];
LCL ChrT MAIN_var9[14];
LCL FbldT _MAIN_Fld[]={
 {"",0,0, MAIN_var1,1,30,
  "9999999",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, MAIN_var2,2,30,
  "9999999",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, MAIN_var3,3,30,
  "9999999",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, MAIN_var4,5,30,
  "**********",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var5,6,30,
  "*************",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var6,8,30,
  "*************",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, MAIN_var7,9,30,
  "9999",NULL,NULL,NULL,
  0,7,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, MAIN_var8,10,30,
  "9999",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, MAIN_var9,11,30,
  "*************",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _MAIN_Frm={
 _MAIN_Fld,9,NULL,NULL,10,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _MAIN_2STR(NOARG)
{
  cvtic(MAIN_var1,AllMem,7);
  cvtic(MAIN_var2,UseMem,7);
  cvtic(MAIN_var3,FreeMem,7);
  strcpy(MAIN_var4,DispType); strsetsz(MAIN_var4,10);
  strcpy(MAIN_var5,KeybType); strsetsz(MAIN_var5,13);
  strcpy(MAIN_var6,CurName); strsetsz(MAIN_var6,13);
  cvtic(MAIN_var7,UseSys,4);
  cvtic(MAIN_var8,UseGen,4);
  strcpy(MAIN_var9,Status); strsetsz(MAIN_var9,13);
 return;
}
VOID CTYP EDT_INFO(NOARG)
{
 Wopen(6,21,21,66,BOX_DBL,
       _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,17,_BLUE|INTENSE|LGREY,'╡');
  Wmessage("Информация",BRD_TOP,18,_BLUE|LGREY);
  Wbprintc(BRD_TOP,28,_BLUE|INTENSE|LGREY,'╞');
  Wprts(1,2,_BLUE|LGREY,"Всего памяти");
  Wprts(1,15,_BLUE|LGREY,".............");
  Wprts(1,36,_BLUE|LGREY,"  Kb");
  Wprts(2,2,_BLUE|LGREY,"Используется");
  Wprts(2,15,_BLUE|LGREY,".............");
  Wprts(2,36,_BLUE|LGREY,"  Kb");
  Wprts(3,0,_BLUE|LGREY,"  Свободной памяти .........  ");
  Wprts(3,35,_BLUE|LGREY,"   Kb");
  Wprts(4,0,_BLUE|LGREY," ");
  Wprts(5,2,_BLUE|LGREY,"Графический адаптер ......");
  Wprts(6,1,_BLUE|LGREY," Тип манипулятора ......... ");
  Wprts(7,1,_BLUE|LGREY," ");
  Wprts(8,1,_BLUE|LGREY," Динамическая система ..... ");
  Wprts(9,1,_BLUE|LGREY," Использовано п/систем .... ");
  Wprts(10,1,_BLUE|LGREY," Сложные генераторы ....... ");
  Wprts(11,2,_BLUE|LGREY,"Статус ................... ");
  Wprts(13,0,_LGREY|BLACK,"           Нажмите любую клавишу            ");

  _MAIN_2STR();
  EntPush();
  EntBuild(&_MAIN_Frm);
  EntDsp();
  EntFree();
  EntPop();

 MouPush(MOU_FULL);
 CurHide();
 KeyWait();
 CurShow();
 MouPop();
 Wclose();
  return;
}

/*** END OF FILE ***/
