

/*
 *   Generated by  UI v2.00 
 *        September 9, 1993
 */


/* Module: MENU\EDT_NEW.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;

#include "dsys.h"
#include "menu.h"
#include "string.h"
static char filename[80];
static char pic[80]="NONAME.DSF";


VOID CTYP _set_EXEC(NOARG);
VOID CTYP _use_EXEC(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);


LCL ChrT main_var1[56];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var1,1,1,
  "*******************************************************",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,1,NULL,NULL,2,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(5,16,9,74,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,18,_BLUE|LGREY,'┤');
  Wmessage("Новая д.система",BRD_TOP,19,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,34,_BLUE|LGREY,'├');
  Wprts(0,3,_BLUE|LGREY,"Введите");
  Wprts(0,11,_BLUE|LGREY,"имя");
  Wprts(0,15,_BLUE|LGREY,"нового");
  Wprts(0,22,_BLUE|LGREY,"файла");
  Wprts(0,28,_BLUE|LGREY,":");

  _main_2STR();
  EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  strcpy(main_var1,filename); strsetsz(main_var1,55);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    strcpy(filename,main_var1);
 return;
}

LCL VOID CTYP _set_EXEC(NOARG)
{
 filename[0]=0;                    
  return;
}
LCL VOID CTYP _use_EXEC(NOARG)
{
if(filename[0]) EdtNewScr(filename);     
  return;
}
VOID CTYP EDT_NEW(NOARG)
{
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _set_EXEC();
 _main_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _main_2STR();
 EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
  _use_EXEC();
}
  return;
}

/*** END OF FILE ***/
