

/*
 *   Generated by  UI v2.00 
 *        June 14, 1993
 */


/* Module: MENU\EDT_ZVEN.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "dsys.h"
#include "menu.h"



VOID CTYP _EasyZveno_WRITE(NOARG);
VOID CTYP _EasyGen_WRITE(NOARG);
VOID CTYP _BegSys_WRITE(NOARG);
VOID CTYP _DifZveno_WRITE(NOARG);
VOID CTYP _DifGen_WRITE(NOARG);
VOID CTYP _EndSys_WRITE(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);
VOID CTYP _EasyZveno_2STR(NOARG);
VOID CTYP _EasyGen_2STR(NOARG);
VOID CTYP _BegSys_2STR(NOARG);
VOID CTYP _DifZveno_2STR(NOARG);
VOID CTYP _DifGen_2STR(NOARG);
VOID CTYP _EndSys_2STR(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
EdtPutBlock(EASY_ZVENO);
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
EdtPutBlock(EASY_GEN);
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
EdtPutBlock(DSYS_BEG);
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
EdtPutBlock(DIF_ZVENO);
return;
}

LCL VOID CTYP _opt5_ACT(NOARG)
{
EdtPutBlock(DIF_GEN);
return;
}

LCL VOID CTYP _opt6_ACT(NOARG)
{
EdtPutBlock(DSYS_END);
return;
}

LCL IbldT _MAIN_Itm[]={
{"  Простое звено  ",'',ITM_NOR|ITM_BEF,1,1,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{"Простой генератор",'',ITM_NOR|ITM_BEF,1,21,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{"   Вход системы  ",'',ITM_NOR|ITM_BEF,1,41,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   "",NULL},
{"  Сложное звено  ",'',ITM_NOR|ITM_BEF,7,1,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   "",NULL},
{"Сложный генератор",'',ITM_NOR|ITM_BEF,7,21,  9,HLP_NONE,
   0,10,NULL,_opt5_ACT,NULL,
   "",NULL},
{"  Выход системы  ",'',ITM_NOR|ITM_BEF,7,41,  11,HLP_NONE,
   0,12,NULL,_opt6_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,6,6,9,20,69,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_DBL,
   _BLUE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_MAIN_MSG,13, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,21,_BLUE|LGREY,'╡');
  Wmessage("Звенья д.системы",BRD_TOP,22,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,38,_BLUE|LGREY,'╞');
  Wprts(2,5,_BLUE|LGREY,"  Alt-Z  ");
  Wprts(2,25,_BLUE|LGREY," Alt-G ");
  Wprts(2,47,_BLUE|LGREY,"Alt-B ");
  Wprts(8,6,_BLUE|LGREY," Alt-W  ");
  Wprts(8,26,_BLUE|LGREY,"Alt-F ");
  Wprts(8,47,_BLUE|LGREY,"Alt-E ");
  {
  MnuDsp(&_MAIN_Mnu);
  }
{
 extern struct _WDEF WDEF_EasyZveno;

struct _WDEF _WDEF_EasyZveno=
    {16,10,22,12,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_EasyZveno,&_WDEF_EasyZveno,sizeof(WDEF_EasyZveno));
}
  _EasyZveno_WRITE();
{
 extern struct _WDEF WDEF_EasyGen;

struct _WDEF _WDEF_EasyGen=
    {35,10,41,12,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_EasyGen,&_WDEF_EasyGen,sizeof(WDEF_EasyGen));
}
  _EasyGen_WRITE();
{
 extern struct _WDEF WDEF_BegSys;

struct _WDEF _WDEF_BegSys=
    {56,10,62,12,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_BegSys,&_WDEF_BegSys,sizeof(WDEF_BegSys));
}
  _BegSys_WRITE();
{
 extern struct _WDEF WDEF_DifZveno;

struct _WDEF _WDEF_DifZveno=
    {16,16,22,18,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_DifZveno,&_WDEF_DifZveno,sizeof(WDEF_DifZveno));
}
  _DifZveno_WRITE();
{
 extern struct _WDEF WDEF_DifGen;

struct _WDEF _WDEF_DifGen=
    {35,16,41,18,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_DifGen,&_WDEF_DifGen,sizeof(WDEF_DifGen));
}
  _DifGen_WRITE();
{
 extern struct _WDEF WDEF_EndSys;

struct _WDEF _WDEF_EndSys=
    {56,16,62,18,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_EndSys,&_WDEF_EndSys,sizeof(WDEF_EndSys));
}
  _EndSys_WRITE();
  return;
}

struct _WDEF WDEF_EasyZveno=
    {16,10,22,12,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _EasyZveno_WRITE(NOARG)
{
 Wopen(WDEF_EasyZveno.BegR,WDEF_EasyZveno.BegC,
       WDEF_EasyZveno.EndR,WDEF_EasyZveno.EndC,
       WDEF_EasyZveno.FrmT,WDEF_EasyZveno.FrmA,WDEF_EasyZveno.Dat);
 if(WDEF_EasyZveno.Shadow) Wshadow(WDEF_EasyZveno.Sat);
 CurHide();
  Wprts(0,1,_CYAN|INTENSE|CYAN,"┌───┐");
  Wprts(1,0,_CYAN|INTENSE|CYAN,"─┤W()├─");
  Wprts(2,1,_CYAN|INTENSE|CYAN,"└───┘");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_EasyGen=
    {35,10,41,12,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _EasyGen_WRITE(NOARG)
{
 Wopen(WDEF_EasyGen.BegR,WDEF_EasyGen.BegC,
       WDEF_EasyGen.EndR,WDEF_EasyGen.EndC,
       WDEF_EasyGen.FrmT,WDEF_EasyGen.FrmA,WDEF_EasyGen.Dat);
 if(WDEF_EasyGen.Shadow) Wshadow(WDEF_EasyGen.Sat);
 CurHide();
  Wprts(0,1,_CYAN|INTENSE|CYAN,"┌───┐");
  Wprts(1,1,_CYAN|INTENSE|CYAN,"│G()├─");
  Wprts(2,1,_CYAN|INTENSE|CYAN,"└───┘");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_BegSys=
    {56,10,62,12,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _BegSys_WRITE(NOARG)
{
 Wopen(WDEF_BegSys.BegR,WDEF_BegSys.BegC,
       WDEF_BegSys.EndR,WDEF_BegSys.EndC,
       WDEF_BegSys.FrmT,WDEF_BegSys.FrmA,WDEF_BegSys.Dat);
 if(WDEF_BegSys.Shadow) Wshadow(WDEF_BegSys.Sat);
 CurHide();
  Wprts(0,1,_CYAN|INTENSE|CYAN,"╔═══╗");
  Wprts(1,1,_CYAN|INTENSE|CYAN,"║");
  Wprts(1,2,_CYAN|BROWN,"BEG");
  Wprts(1,5,_CYAN|INTENSE|CYAN,"╟─");
  Wprts(2,1,_CYAN|INTENSE|CYAN,"╚═══╝");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_DifZveno=
    {16,16,22,18,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _DifZveno_WRITE(NOARG)
{
 Wopen(WDEF_DifZveno.BegR,WDEF_DifZveno.BegC,
       WDEF_DifZveno.EndR,WDEF_DifZveno.EndC,
       WDEF_DifZveno.FrmT,WDEF_DifZveno.FrmA,WDEF_DifZveno.Dat);
 if(WDEF_DifZveno.Shadow) Wshadow(WDEF_DifZveno.Sat);
 CurHide();
  Wprts(0,1,_CYAN|INTENSE|CYAN,"╔═══╗");
  Wprts(1,0,_CYAN|INTENSE|CYAN,"─╢W()╟─");
  Wprts(2,1,_CYAN|INTENSE|CYAN,"╚═══╝");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_DifGen=
    {35,16,41,18,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _DifGen_WRITE(NOARG)
{
 Wopen(WDEF_DifGen.BegR,WDEF_DifGen.BegC,
       WDEF_DifGen.EndR,WDEF_DifGen.EndC,
       WDEF_DifGen.FrmT,WDEF_DifGen.FrmA,WDEF_DifGen.Dat);
 if(WDEF_DifGen.Shadow) Wshadow(WDEF_DifGen.Sat);
 CurHide();
  Wprts(0,1,_CYAN|INTENSE|CYAN,"╔═══╗");
  Wprts(1,1,_CYAN|INTENSE|CYAN,"║G()╟─");
  Wprts(2,1,_CYAN|INTENSE|CYAN,"╚═══╝");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_EndSys=
    {56,16,62,18,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _EndSys_WRITE(NOARG)
{
 Wopen(WDEF_EndSys.BegR,WDEF_EndSys.BegC,
       WDEF_EndSys.EndR,WDEF_EndSys.EndC,
       WDEF_EndSys.FrmT,WDEF_EndSys.FrmA,WDEF_EndSys.Dat);
 if(WDEF_EndSys.Shadow) Wshadow(WDEF_EndSys.Sat);
 CurHide();
  Wprts(0,1,_CYAN|INTENSE|CYAN,"╔═══╗");
  Wprts(1,0,_CYAN|INTENSE|CYAN,"─╢");
  Wprts(1,2,_CYAN|BROWN,"END");
  Wprts(1,5,_CYAN|INTENSE|CYAN,"║");
  Wprts(2,1,_CYAN|INTENSE|CYAN,"╚═══╝");
 Wunlink(Whandle());
 return;
}
VOID CTYP EDT_ZVEN(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_MAIN_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
