

/*
 *   Generated by  UI v2.00 
 *        September 27, 1993
 */


/* Module: MENU\EDT_LINE.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "dsys.h"
#include "menu.h"



VOID CTYP _Hor_WRITE(NOARG);
VOID CTYP _Left_WRITE(NOARG);
VOID CTYP _Point_WRITE(NOARG);
VOID CTYP _Ver_WRITE(NOARG);
VOID CTYP _Right_WRITE(NOARG);
VOID CTYP _None_WRITE(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);
VOID CTYP _Hor_2STR(NOARG);
VOID CTYP _Left_2STR(NOARG);
VOID CTYP _Point_2STR(NOARG);
VOID CTYP _Ver_2STR(NOARG);
VOID CTYP _Right_2STR(NOARG);
VOID CTYP _None_2STR(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
EdtPutBlock(BLK_HOR);
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
EdtPutBlock(BLK_LEFT);
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
EdtPutBlock(BLK_NTR);
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
EdtPutBlock(BLK_VER);
return;
}

LCL VOID CTYP _opt5_ACT(NOARG)
{
EdtPutBlock(BLK_RIGHT);
return;
}

LCL VOID CTYP _opt6_ACT(NOARG)
{
EdtPutBlock(BLK_NONE);
return;
}

LCL IbldT _MAIN_Itm[]={
{" Горизонтальное",'',ITM_NOR|ITM_BEF,1,3,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{"  Левый угол   ",'',ITM_NOR|ITM_BEF,1,21,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{"     Узел      ",'',ITM_NOR|ITM_BEF,1,39,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   "",NULL},
{" Вертикальное  ",'',ITM_NOR|ITM_BEF,7,3,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   "",NULL},
{"  Правый угол  ",'',ITM_NOR|ITM_BEF,7,21,  9,HLP_NONE,
   0,10,NULL,_opt5_ACT,NULL,
   "",NULL},
{"  Пустое место ",'',ITM_NOR|ITM_BEF,7,39,  11,HLP_NONE,
   0,12,NULL,_opt6_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,6,7,10,21,68,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_DBL,
   _BLUE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_MAIN_MSG,13, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,18,_BLUE|LGREY,'╡');
  Wmessage("Соединения д.системы",BRD_TOP,19,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,39,_BLUE|LGREY,'╞');
  Wprts(2,8,_BLUE|LGREY,"Alt-H");
  Wprts(2,26,_BLUE|LGREY,"Alt-L");
  Wprts(2,44,_BLUE|LGREY,"Alt-P ");
  Wprts(8,8,_BLUE|LGREY,"Alt-V ");
  Wprts(8,26,_BLUE|LGREY,"Alt-R ");
  Wprts(8,44,_BLUE|LGREY,"Alt-N");
  {
  MnuDsp(&_MAIN_Mnu);
  }
{
 extern struct _WDEF WDEF_Hor;

struct _WDEF _WDEF_Hor=
    {18,11,24,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Hor,&_WDEF_Hor,sizeof(WDEF_Hor));
}
  _Hor_WRITE();
{
 extern struct _WDEF WDEF_Left;

struct _WDEF _WDEF_Left=
    {36,11,42,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Left,&_WDEF_Left,sizeof(WDEF_Left));
}
  _Left_WRITE();
{
 extern struct _WDEF WDEF_Point;

struct _WDEF _WDEF_Point=
    {54,11,60,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Point,&_WDEF_Point,sizeof(WDEF_Point));
}
  _Point_WRITE();
{
 extern struct _WDEF WDEF_Ver;

struct _WDEF _WDEF_Ver=
    {18,17,24,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Ver,&_WDEF_Ver,sizeof(WDEF_Ver));
}
  _Ver_WRITE();
{
 extern struct _WDEF WDEF_Right;

struct _WDEF _WDEF_Right=
    {36,17,42,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_Right,&_WDEF_Right,sizeof(WDEF_Right));
}
  _Right_WRITE();
{
 extern struct _WDEF WDEF_None;

struct _WDEF _WDEF_None=
    {54,17,60,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 memcpy(&WDEF_None,&_WDEF_None,sizeof(WDEF_None));
}
  _None_WRITE();
  return;
}

struct _WDEF WDEF_Hor=
    {18,11,24,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Hor_WRITE(NOARG)
{
 Wopen(WDEF_Hor.BegR,WDEF_Hor.BegC,
       WDEF_Hor.EndR,WDEF_Hor.EndC,
       WDEF_Hor.FrmT,WDEF_Hor.FrmA,WDEF_Hor.Dat);
 if(WDEF_Hor.Shadow) Wshadow(WDEF_Hor.Sat);
 CurHide();
  Wprts(1,0,_CYAN|INTENSE|CYAN,"───────");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_Left=
    {36,11,42,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Left_WRITE(NOARG)
{
 Wopen(WDEF_Left.BegR,WDEF_Left.BegC,
       WDEF_Left.EndR,WDEF_Left.EndC,
       WDEF_Left.FrmT,WDEF_Left.FrmA,WDEF_Left.Dat);
 if(WDEF_Left.Shadow) Wshadow(WDEF_Left.Sat);
 CurHide();
  Wprts(0,3,_CYAN|INTENSE|CYAN,"│");
  Wprts(1,3,_CYAN|INTENSE|CYAN,"└───");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_Point=
    {54,11,60,13,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Point_WRITE(NOARG)
{
 Wopen(WDEF_Point.BegR,WDEF_Point.BegC,
       WDEF_Point.EndR,WDEF_Point.EndC,
       WDEF_Point.FrmT,WDEF_Point.FrmA,WDEF_Point.Dat);
 if(WDEF_Point.Shadow) Wshadow(WDEF_Point.Sat);
 CurHide();
  Wprts(1,0,_CYAN|INTENSE|CYAN,"───┬───");
  Wprts(2,3,_CYAN|INTENSE|CYAN,"│");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_Ver=
    {18,17,24,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Ver_WRITE(NOARG)
{
 Wopen(WDEF_Ver.BegR,WDEF_Ver.BegC,
       WDEF_Ver.EndR,WDEF_Ver.EndC,
       WDEF_Ver.FrmT,WDEF_Ver.FrmA,WDEF_Ver.Dat);
 if(WDEF_Ver.Shadow) Wshadow(WDEF_Ver.Sat);
 CurHide();
  Wprts(0,3,_CYAN|INTENSE|CYAN,"│");
  Wprts(1,3,_CYAN|INTENSE|CYAN,"│");
  Wprts(2,3,_CYAN|INTENSE|CYAN,"│");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_Right=
    {36,17,42,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _Right_WRITE(NOARG)
{
 Wopen(WDEF_Right.BegR,WDEF_Right.BegC,
       WDEF_Right.EndR,WDEF_Right.EndC,
       WDEF_Right.FrmT,WDEF_Right.FrmA,WDEF_Right.Dat);
 if(WDEF_Right.Shadow) Wshadow(WDEF_Right.Sat);
 CurHide();
  Wprts(0,3,_CYAN|INTENSE|CYAN,"│");
  Wprts(1,0,_CYAN|INTENSE|CYAN,"───┘");
 Wunlink(Whandle());
 return;
}

struct _WDEF WDEF_None=
    {54,17,60,19,0,0,0,0,
     BOX_SPA,_CYAN|INTENSE|CYAN,
     _CYAN|INTENSE|CYAN,0,_BLACK|DGREY};

 VOID CTYP _None_WRITE(NOARG)
{
 Wopen(WDEF_None.BegR,WDEF_None.BegC,
       WDEF_None.EndR,WDEF_None.EndC,
       WDEF_None.FrmT,WDEF_None.FrmA,WDEF_None.Dat);
 if(WDEF_None.Shadow) Wshadow(WDEF_None.Sat);
 CurHide();
 Wunlink(Whandle());
 return;
}
VOID CTYP EDT_LINE(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_MAIN_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
