

/*
 *   Generated by  UI v2.00 
 *        May 15, 1993
 */


/* Module: MENU\GEN_E.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
LCL  IntT EntResult;
#include "string.h"
#include "menu.h"

extern EasyGenT GenBuf[];
extern GenT UseGen;


VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
InitEasyGenParam();
UseGen=ParBuf.U.EasyGen.Gen;
memcpy(&GenBuf[UseGen],&ParBuf.U.EasyGen,sizeof(EasyGenT));
MOD_TEST();  GenBuf[UseGen].Gen=UseGen;
memcpy(&ParBuf.U.EasyGen,&GenBuf[UseGen],sizeof(EasyGenT));
return;
}

LCL IbldT _main_Itm[]={
{"   Тестовые воздействия    ",'',ITM_NOR|ITM_AFT,1,2,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{"   Оригинальные сигналы    ",'',ITM_NOR|ITM_NSL,3,2,  3,HLP_NONE,
   0,4,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,2,2,16,8,48,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_main_MSG,5, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Генератор├",BRD_TOP,11,_BLUE|INTENSE|LGREY);
  {
  extern MbldT _main_Mnu;
  MnuDsp(&_main_Mnu);
  }
  return;
}
VOID CTYP GEN_E(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_main_Mnu)=IbldTag(&_main_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_main_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
