

/*
 *   Generated by  UI v2.00 
 *        November 1, 1993
 */


/* Module: MENU\MAIN_MNU.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include <stdio.h>

#include "dsys.h"    // глобальные типы и переменные
#include "help.h"    // помощь
#include "menu.h"    // функции главного меню
#include "copyrite.h"
VOID CTYP CFG_ARC(NOARG);
VOID CTYP SHOW_RES(NOARG);
VOID CTYP ARCHIVE(NOARG);

VOID CTYP _TopMnu_MENU(NOARG);
VOID CTYP _TopMnu_MENU(NOARG);
VOID CTYP _ExitMnu_MENU(NOARG);
VOID CTYP _Edt_WRITE(NOARG);
VOID CTYP _FKey_WRITE(NOARG);
VOID CTYP _TopMnu_WRITE(NOARG);
VOID CTYP _title_EXEC(NOARG);
VOID CTYP _EdtLoop_EXEC(NOARG);
VOID CTYP _About_SHOW(NOARG);
VOID CTYP _EdtMnu_MENU(NOARG);
VOID CTYP _ModMnu_MENU(NOARG);
VOID CTYP _ResMnu_MENU(NOARG);
VOID CTYP _CfgMnu_MENU(NOARG);
VOID CTYP _ExitMnu_MENU(NOARG);
VOID CTYP _INFO_SET_WRITE(NOARG);
VOID CTYP _INFO_CLR_WRITE(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _TopMnu_2STR(NOARG);
VOID CTYP _TopMnu_MSG(NOARG);
VOID CTYP _ExitMnu_2STR(NOARG);
VOID CTYP _ExitMnu_MSG(NOARG);
VOID CTYP _Edt_2STR(NOARG);
VOID CTYP _FKey_2STR(NOARG);
VOID CTYP _About_2STR(NOARG);
VOID CTYP _EdtMnu_2STR(NOARG);
VOID CTYP _EdtMnu_MSG(NOARG);
VOID CTYP _ModMnu_2STR(NOARG);
VOID CTYP _ModMnu_MSG(NOARG);
VOID CTYP _ResMnu_2STR(NOARG);
VOID CTYP _ResMnu_MSG(NOARG);
VOID CTYP _CfgMnu_2STR(NOARG);
VOID CTYP _CfgMnu_MSG(NOARG);
VOID CTYP _INFO_SET_2STR(NOARG);
VOID CTYP _INFO_CLR_2STR(NOARG);


LCL VOID CTYP _opt28_ACT(NOARG)
{
EdtExit();
return;
}

LCL IbldT _ExitMnu_Itm[]={
{"  ДА   ",'',ITM_NOR|ITM_AFT,1,5,  1,HLP_NONE,
   0,2,NULL,_opt28_ACT,NULL,
   "",NULL},
{"  НЕТ  ",'',ITM_NOR|ITM_AFT,1,21,  3,HLP_NONE,
   0,4,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _ExitMnu_MSG(NOARG);
LCL MbldT _ExitMnu_Mnu={
   _ExitMnu_Itm,2,10,22,14,56,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_DBL,
   _RED|INTENSE|LGREY,_RED|INTENSE|LGREY,_RED|INTENSE|LGREY,
   _RED|BLACK,_RED|BLACK,_LGREY|BLACK,
   0,_ExitMnu_MSG,5, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _ExitMnu_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("╡Закончить работу╞",BRD_TOP,8,_RED|INTENSE|LGREY);
  Wprts(0,3,_RED|INTENSE|LGREY,"┌─────────┐");
  Wprts(0,19,_RED|INTENSE|LGREY,"┌─────────┐");
  Wprts(1,3,_RED|INTENSE|LGREY,"│");
  Wprts(1,13,_RED|INTENSE|LGREY,"│");
  Wprts(1,19,_RED|INTENSE|LGREY,"│");
  Wprts(1,29,_RED|INTENSE|LGREY,"│");
  Wprts(2,3,_RED|INTENSE|LGREY,"└─────────┘");
  Wprts(2,19,_RED|INTENSE|LGREY,"└─────────┘");
  {
  MnuDsp(&_ExitMnu_Mnu);
  }
  return;
}
LCL VOID CTYP _ExitMnu_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_ExitMnu_Mnu)=IbldTag(&_ExitMnu_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_ExitMnu_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
LCL VOID CTYP _Edt_WRITE(NOARG)
{
 Wopen(1,0,23,78,BOX_DBL,
       _CYAN|INTENSE|LGREY,_CYAN|BLACK);
 CurHide();
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
  _INFO_SET_WRITE();
  _INFO_CLR_WRITE();
 KbndChg(tcxl_old_kb);
   }
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _FKey_WRITE(NOARG)
{
 Wopen(24,0,24,79,BOX_SPA,
       _BLUE|LGREY,_BLUE|LGREY);
 CurHide();
  Wprts(0,0,_BLUE|INTENSE|RED,"F1");
  Wprts(0,3,_BLUE|LGREY,"Помощь");
  Wprts(0,10,_BLUE|INTENSE|RED,"F2 ");
  Wprts(0,13,_BLUE|LGREY,"Сохранить");
  Wprts(0,23,_BLUE|INTENSE|RED,"F3 ");
  Wprts(0,26,_BLUE|LGREY,"Загрузить");
  Wprts(0,36,_BLUE|INTENSE|RED,"F4 ");
  Wprts(0,39,_BLUE|LGREY,"Моделирование");
  Wprts(0,53,_BLUE|INTENSE|RED,"F7 ");
  Wprts(0,56,_BLUE|LGREY,"Графика");
  Wprts(0,64,_BLUE|INTENSE|RED,"F10 ");
  Wprts(0,68,_BLUE|LGREY,"Меню");
  Wprts(0,72,_BLUE|BLACK," ");
  Wprts(0,73,_BLUE|LGREY,"│");
  Wprts(0,74,_BLUE|INTENSE|LGREY,"DSYS");
  Wprts(0,79,_BLACK|INTENSE|LGREY," ");
 Wunlink(Whandle());
 return;
}
LCL VOID CTYP _title_EXEC(NOARG)
{
fprintf(stdout,"\nDSYS Editor " _VERSION_                              
       " Copyright (C) Samara-\"Trend\" " _YEAR_ ".\n");               
                                                                       
  return;
}
LCL VOID CTYP _EdtLoop_EXEC(NOARG)
{
EdtLoop(); 
  return;
}
LCL VOID CTYP _About_SHOW(NOARG)
{
 Wopen(7,12,18,67,BOX_SNG,
       _BLUE|INTENSE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤About├",BRD_TOP,24,_BLUE|INTENSE|LGREY);
  Wprts(1,10,_BLUE|LGREY,"Моделирование");
  Wprts(1,24,_BLUE|LGREY,"динамических");
  Wprts(1,37,_BLUE|LGREY,"систем");
  Wprts(2,22,_BLUE|LGREY,"DSYS");
  Wprts(2,27,_BLUE|LGREY,"v0.01");
  Wprts(3,17,_BLUE|LGREY,"СамПтУ");
  Wprts(3,24,_BLUE|LGREY,"каф");
  Wprts(3,28,_BLUE|LGREY,"ИТ");
  Wprts(3,31,_BLUE|LGREY,"1993.");
  Wprts(5,5,_BLUE|LGREY,"Разработчик:");
  Wprts(5,20,_BLUE|LGREY,"Д.Ю.");
  Wprts(5,25,_BLUE|LGREY,"Кокорев");
  Wprts(6,5,_BLUE|LGREY,"Руководители:");
  Wprts(6,20,_BLUE|LGREY,"В.В.");
  Wprts(6,25,_BLUE|LGREY,"Волков");
  Wprts(7,20,_BLUE|LGREY,"Е.П.");
  Wprts(7,25,_BLUE|LGREY,"Черкасский");
  Wprts(9,0,_LGREY|BLACK,"                Нажмите любую клавишу                 ");
 MouPush(MOU_FULL);
 CurHide();
 KeyWait();
 CurShow();
 MouPop();
 Wclose();
 return;
}

LCL VOID CTYP _opt7_ACT(NOARG)
{
EDT_LOAD();
return;
}

LCL VOID CTYP _opt11_ACT(NOARG)
{
EDT_SAVE();
return;
}

LCL VOID CTYP _opt15_ACT(NOARG)
{
EDT_NEW();
return;
}

LCL VOID CTYP _opt16_ACT(NOARG)
{
VOID CTYP SAVE_AS(NOARG);
SAVE_AS();
return;
}

LCL VOID CTYP _opt20_ACT(NOARG)
{
EDT_ZVEN();
KquePut(Key_C_Q);
return;
}

LCL VOID CTYP _opt23_ACT(NOARG)
{
EDT_POIN();
KquePut(Key_C_Q);
return;
}

LCL VOID CTYP _opt25_ACT(NOARG)
{
EDT_LINE();
KquePut(Key_C_Q);
return;
}

LCL VOID CTYP _opt26_ACT(NOARG)
{
EDT_INFO();
return;
}

LCL IbldT _EdtMnu_Itm[]={
{" Загрузить д.систему   F3       ",'',ITM_NOR|ITM_ALL|ITM_BEF,0,0,  6,HLP_NONE,
   0,7,NULL,_opt7_ACT,NULL,
   "",NULL},
{" Сохранить д.систему   F2       ",'',ITM_NOR|ITM_ALL,1,0,  8,HLP_NONE,
   0,9,NULL,_opt11_ACT,NULL,
   "",NULL},
{" Новая д.система       Shift-F3 ",'',ITM_NOR|ITM_ALL|ITM_BEF,2,0,  10,HLP_NONE,
   0,11,NULL,_opt15_ACT,NULL,
   "",NULL},
{" Сохранить как ...     Shift-F2 ",'',ITM_NOR|ITM_ALL|ITM_BEF,3,0,  12,HLP_NONE,
   0,13,NULL,_opt16_ACT,NULL,
   "",NULL},
{" Динамические звенья   Сtrl-Z   ",'',ITM_NOR|ITM_ALL,5,0,  14,HLP_NONE,
   0,15,NULL,_opt20_ACT,NULL,
   "",NULL},
{" Арифметические узлы   Ctrl-A   ",'',ITM_NOR|ITM_ALL,6,0,  16,HLP_NONE,
   0,17,NULL,_opt23_ACT,NULL,
   "",NULL},
{" Соединения звеньев    Ctrl-L   ",'',ITM_NOR|ITM_ALL,7,0,  18,HLP_NONE,
   0,19,NULL,_opt25_ACT,NULL,
   "",NULL},
{" Информация            Ctrl-I   ",'',ITM_NOR|ITM_ALL|ITM_BEF,9,0,  20,HLP_NONE,
   0,21,NULL,_opt26_ACT,NULL,
   "",NULL},
{" Рабочая директория             ",'',ITM_NOR|ITM_NSL,10,0,  22,HLP_NONE,
   0,23,NULL,NULL,NULL,
   "",NULL},
{" Временный выход в DOS Ctrl-D   ",'',ITM_NOR|ITM_NSL,11,0,  24,HLP_NONE,
   0,25,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _EdtMnu_MSG(NOARG);
LCL MbldT _EdtMnu_Mnu={
   _EdtMnu_Itm,10,1,8,14,41,  MNU_PUL|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_EdtMnu_MSG,26, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _EdtMnu_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_LFT,5,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_LFT,9,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_RGT,5,_BLUE|INTENSE|LGREY,'┤');
  Wbprintc(BRD_RGT,9,_BLUE|INTENSE|LGREY,'┤');
  Wprts(4,0,_BLUE|INTENSE|LGREY,"────────────────────────────────");
  Wprts(8,0,_BLUE|INTENSE|LGREY,"────────────────────────────────");
  {
  MnuDsp(&_EdtMnu_Mnu);
  }
  return;
}
LCL VOID CTYP _EdtMnu_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_EdtMnu_Mnu)=IbldTag(&_EdtMnu_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_EdtMnu_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt12_ACT(NOARG)
{
MOD_PROC();
return;
}

LCL VOID CTYP _opt17_ACT(NOARG)
{
InitEasyGenParam();
MOD_TEST();
StoreEasyGenParam();
return;
}

LCL VOID CTYP _opt21_ACT(NOARG)
{
MOD_GLB();
return;
}

LCL IbldT _ModMnu_Itm[]={
{" По сценарию          ",'',ITM_NOR|ITM_NSL|ITM_BEF,0,0,  27,HLP_NONE,
   0,28,NULL,NULL,NULL,
   "",NULL},
{" Импульсная хар-ка    ",'',ITM_NOR|ITM_BEF,1,0,  29,HLP_NONE,
   0,30,NULL,_opt12_ACT,NULL,
   "",NULL},
{" Тестовые вх. сигналы ",'',ITM_NOR,3,0,  31,HLP_NONE,
   0,32,NULL,_opt17_ACT,NULL,
   "",NULL},
{" Внешние вх. сигналы  ",'',ITM_NOR|ITM_NSL,4,0,  33,HLP_NONE,
   0,34,NULL,NULL,NULL,
   "",NULL},
{" Параметры модели     ",'',ITM_NOR,5,0,  35,HLP_NONE,
   0,36,NULL,_opt21_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _ModMnu_MSG(NOARG);
LCL MbldT _ModMnu_Mnu={
   _ModMnu_Itm,5,1,22,8,45,  MNU_PUL|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_ModMnu_MSG,37, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _ModMnu_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_LFT,3,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_RGT,3,_BLUE|INTENSE|LGREY,'┤');
  Wprts(2,0,_BLUE|INTENSE|LGREY,"──────────────────────");
  {
  MnuDsp(&_ModMnu_Mnu);
  }
  return;
}
LCL VOID CTYP _ModMnu_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_ModMnu_Mnu)=IbldTag(&_ModMnu_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_ModMnu_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt9_ACT(NOARG)
{
SHOW_RES();
return;
}

LCL VOID CTYP _opt13_ACT(NOARG)
{
ARCHIVE();
return;
}

LCL IbldT _ResMnu_Itm[]={
{" Просмотр результатов  ",'',ITM_NOR,0,0,  38,HLP_NONE,
   0,39,NULL,_opt9_ACT,NULL,
   "",NULL},
{" Ведение архива данных ",'',ITM_NOR,1,0,  40,HLP_NONE,
   0,41,NULL,_opt13_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _ResMnu_MSG(NOARG);
LCL MbldT _ResMnu_Mnu={
   _ResMnu_Itm,2,1,40,4,64,  MNU_PUL|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_ResMnu_MSG,42, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _ResMnu_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  {
  MnuDsp(&_ResMnu_Mnu);
  }
  return;
}
LCL VOID CTYP _ResMnu_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_ResMnu_Mnu)=IbldTag(&_ResMnu_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_ResMnu_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt10_ACT(NOARG)
{
CFG_MOD();
return;
}

LCL VOID CTYP _opt14_ACT(NOARG)
{
CFG_RES();
return;
}

LCL VOID CTYP _opt18_ACT(NOARG)
{
CFG_DIR();
return;
}

LCL VOID CTYP _opt22_ACT(NOARG)
{
SAVE_CFG();
return;
}

LCL VOID CTYP _opt24_ACT(NOARG)
{
LOAD_CFG();
return;
}

LCL IbldT _CfgMnu_Itm[]={
{" Моделирование  ",'',ITM_NOR,0,0,  43,HLP_NONE,
   0,44,NULL,_opt10_ACT,NULL,
   "",NULL},
{" Архив данных   ",'',ITM_NOR,1,0,  45,HLP_NONE,
   0,46,NULL,_opt14_ACT,NULL,
   "",NULL},
{" Каталоги       ",'',ITM_NOR,3,0,  47,HLP_NONE,
   0,48,NULL,_opt18_ACT,NULL,
   "",NULL},
{" Сохранение     ",'',ITM_NOR,5,0,  49,HLP_NONE,
   0,50,NULL,_opt22_ACT,NULL,
   "",NULL},
{" Восстановление ",'',ITM_NOR,6,0,  51,HLP_NONE,
   0,52,NULL,_opt24_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _CfgMnu_MSG(NOARG);
LCL MbldT _CfgMnu_Mnu={
   _CfgMnu_Itm,5,1,54,9,71,  MNU_PUL|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_CfgMnu_MSG,53, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _CfgMnu_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_LFT,3,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_LFT,5,_BLUE|INTENSE|LGREY,'├');
  Wbprintc(BRD_RGT,3,_BLUE|INTENSE|LGREY,'┤');
  Wbprintc(BRD_RGT,5,_BLUE|INTENSE|LGREY,'┤');
  Wprts(2,0,_BLUE|INTENSE|LGREY,"────────────────");
  Wprts(4,0,_BLUE|INTENSE|LGREY,"────────────────");
  {
  MnuDsp(&_CfgMnu_Mnu);
  }
  return;
}
LCL VOID CTYP _CfgMnu_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_CfgMnu_Mnu)=IbldTag(&_CfgMnu_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_CfgMnu_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
 VOID CTYP _INFO_SET_WRITE(NOARG)
{
 Wopen(1,3,1,5,BOX_SPA,
       _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY);
 CurHide();
  Wprts(0,0,_CYAN|INTENSE|LGREY,"╡");
  Wprts(0,1,_CYAN|BLACK,"\017" "");
  Wprts(0,2,_CYAN|INTENSE|LGREY,"╞");
 Wunlink(Whandle());
 return;
}
 VOID CTYP _INFO_CLR_WRITE(NOARG)
{
 Wopen(1,3,1,5,BOX_SPA,
       _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY);
 CurHide();
  Wprts(0,0,_CYAN|INTENSE|LGREY,"═══");
 Wunlink(Whandle());
 return;
}

LCL IbldT _TopMnu_Itm[]={
{" (C) ",'',ITM_NOR,0,2,  54,HLP_NONE,
   0,55,NULL,_About_SHOW,NULL,
   "",NULL},
{"  Редактор  ",'',ITM_NOR|ITM_PUL,0,8,  56,HLP_NONE,
   0,57,NULL,NULL,NULL,
   "",&_EdtMnu_Mnu},
{"  Моделирование  ",'',ITM_NOR|ITM_PUL,0,21,  58,HLP_NONE,
   0,59,NULL,NULL,NULL,
   "",&_ModMnu_Mnu},
{"  Результаты  ",'',ITM_NOR|ITM_PUL,0,39,  60,HLP_NONE,
   0,61,NULL,NULL,NULL,
   "",&_ResMnu_Mnu},
{"  Настройка  ",'',ITM_NOR|ITM_PUL,0,54,  62,HLP_NONE,
   0,63,NULL,NULL,NULL,
   "",&_CfgMnu_Mnu},
{"  Выход  ",'',ITM_NOR,0,68,  64,HLP_NONE,
   0,65,NULL,_ExitMnu_MENU,NULL,
   "",NULL},
};


LCL VOID CTYP _TopMnu_MSG(NOARG);
LCL MbldT _TopMnu_Mnu={
   _TopMnu_Itm,6,0,0,0,78,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SPA,
   _BLUE|LGREY,_BLUE|LGREY,_BLUE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_TopMnu_MSG,66, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _TopMnu_MSG(NOARG)
{

 CurHide();
  {
  MnuDsp(&_TopMnu_Mnu);
  }
  return;
}
LCL VOID CTYP _TopMnu_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_TopMnu_Mnu)=IbldTag(&_TopMnu_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_TopMnu_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
LCL VOID CTYP _TopMnu_WRITE(NOARG)
{
 Wopen(0,0,0,78,BOX_SPA,
       _BLUE|LGREY,_BLUE|LGREY);
 _TopMnu_MSG();
  {
  MnuDsp(&_TopMnu_Mnu);
  }
 Wunlink(Whandle());
 return;
}


/*=====================================================================*/


int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
  _title_EXEC();
 Wopen(0,0,24,79,BOX_SPA,
       _CYAN|INTENSE|LGREY,_CYAN|INTENSE|LGREY);
 CurHide();
  Wprts(0,79,_BLACK|INTENSE|LGREY," ");
  Wprts(1,79,_BLACK|INTENSE|LGREY," ");
  Wprts(2,79,_BLACK|INTENSE|LGREY," ");
  Wprts(3,79,_BLACK|INTENSE|LGREY," ");
  Wprts(4,79,_BLACK|INTENSE|LGREY," ");
  Wprts(5,79,_BLACK|INTENSE|LGREY," ");
  Wprts(6,79,_BLACK|INTENSE|LGREY," ");
  Wprts(7,79,_BLACK|INTENSE|LGREY," ");
  Wprts(8,79,_BLACK|INTENSE|LGREY," ");
  Wprts(9,79,_BLACK|INTENSE|LGREY," ");
  Wprts(10,79,_BLACK|INTENSE|LGREY," ");
  Wprts(11,79,_BLACK|INTENSE|LGREY," ");
  Wprts(12,79,_BLACK|INTENSE|LGREY," ");
  Wprts(13,79,_BLACK|INTENSE|LGREY," ");
  Wprts(14,79,_BLACK|INTENSE|LGREY," ");
  Wprts(15,79,_BLACK|INTENSE|LGREY," ");
  Wprts(16,79,_BLACK|INTENSE|LGREY," ");
  Wprts(17,79,_BLACK|INTENSE|LGREY," ");
  Wprts(18,79,_BLACK|INTENSE|LGREY," ");
  Wprts(19,79,_BLACK|INTENSE|LGREY," ");
  Wprts(20,79,_BLACK|INTENSE|LGREY," ");
  Wprts(21,79,_BLACK|INTENSE|LGREY," ");
  Wprts(22,79,_BLACK|INTENSE|LGREY," ");
  Wprts(23,79,_BLACK|INTENSE|LGREY," ");
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
 KbndSet(Key_F10,_TopMnu_MENU,0);
 KbndSet(Key_Esc,_TopMnu_MENU,0);
 KbndSet(Key_A_X,_ExitMnu_MENU,0);
  _Edt_WRITE();
  _FKey_WRITE();
  _TopMnu_WRITE();
  _EdtLoop_EXEC();
 KbndClr(Key_F10);
 KbndClr(Key_Esc);
 KbndClr(Key_A_X);
 KbndChg(tcxl_old_kb);
   }
 Wclose();
  return 0;
}

/*** END OF FILE ***/
