

/*
 *   Generated by  UI v2.00 
 *        September 9, 1993
 */


/* Module: MENU\MOD_GLB.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "dsys.h"
#include "menu.h"

static float GlbLength;
static float GlbChast;
static CfgP cfg;

VOID CTYP _ini_EXEC(NOARG);
VOID CTYP _set_EXEC(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_OPEN(NOARG);


LCL ChrT MAIN_var1[16];
LCL ChrT MAIN_var2[16];
LCL FbldT _MAIN_Fld[]={
 {"",0,0, MAIN_var1,1,18,
  "999999999.99999",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, MAIN_var2,4,18,
  "999999999.99999",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _MAIN_Frm={
 _MAIN_Fld,2,NULL,NULL,3,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _MAIN_OPEN(NOARG)
{

 Wopen(7,30,13,70,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,8,_BLUE|LGREY,'┤');
  Wmessage("Параметры моделирования",BRD_TOP,9,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,32,_BLUE|LGREY,'├');
  Wbprintc(BRD_LFT,3,_BLUE|LGREY,'╟');
  Wbprintc(BRD_RGT,3,_BLUE|LGREY,'╢');
  Wprts(0,1,_BLUE|LGREY,"Длительность");
  Wprts(1,1,_BLUE|LGREY,"моделирования");
  Wprts(1,34,_BLUE|LGREY,"сек.");
  Wprts(2,0,_BLUE|LGREY,"───────────────────────────────────────");
  Wprts(3,1,_BLUE|LGREY,"Частота");
  Wprts(4,1,_BLUE|LGREY,"дискретизации");
  Wprts(4,35,_BLUE|LGREY,"Гц.");

  _MAIN_2STR();
  EntPush();
  EntBuild(&_MAIN_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _MAIN_2STR(NOARG)
{
  cvtfc(MAIN_var1,GlbLength,15,5);
  cvtfc(MAIN_var2,GlbChast,15,5);
 return;
}
LCL VOID CTYP _MAIN_2VAL(NOARG)
{
    GlbLength=cvtcf(MAIN_var1);
    GlbChast=cvtcf(MAIN_var2);
 return;
}

LCL VOID CTYP _ini_EXEC(NOARG)
{
cfg=EdtGetCfg();             
                             
GlbLength=cfg->Glb.Length;   
GlbChast=cfg->Glb.Chast;     
                             
                             
  return;
}
LCL VOID CTYP _set_EXEC(NOARG)
{
if(EntResult)                        
  {                                  
  cfg->Glb.Length=GlbLength;         
  cfg->Glb.Chast=GlbChast;           
  }                                  
  return;
}
VOID CTYP MOD_GLB(NOARG)
{
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _ini_EXEC();
 _MAIN_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _MAIN_2STR();
 EntPush();
 EntBuild(&_MAIN_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_MAIN_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _MAIN_2VAL();
    EntResult=1;
    }
  _set_EXEC();
}
  return;
}

/*** END OF FILE ***/
