

/*
 *   Generated by  UI v2.00 
 *        May 15, 1993
 */


/* Module: MENU\MOD_TEST.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
LCL  IntT EntResult;
#include "dsys.h"
#include "menu.h"
#include "string.h"
EasyGenT GenBuf[10];  // последние данные
GenT   UseGen,tmp;

VOID CTYP _init_EXEC(NOARG);
VOID CTYP _Sin_ENTRY(NOARG);
VOID CTYP _PSin_ENTRY(NOARG);
VOID CTYP _Meandr_ENTRY(NOARG);
VOID CTYP _One_ENTRY(NOARG);
VOID CTYP _Two_ENTRY(NOARG);
VOID CTYP _set_EXEC(NOARG);
VOID CTYP _set_EXEC(NOARG);
VOID CTYP _set_EXEC(NOARG);
VOID CTYP _set_EXEC(NOARG);
VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);
VOID CTYP _Sin_2STR(NOARG);
VOID CTYP _Sin_OPEN(NOARG);
VOID CTYP _PSin_2STR(NOARG);
VOID CTYP _PSin_OPEN(NOARG);
VOID CTYP _Meandr_2STR(NOARG);
VOID CTYP _Meandr_OPEN(NOARG);
VOID CTYP _One_2STR(NOARG);
VOID CTYP _One_OPEN(NOARG);
VOID CTYP _Two_2STR(NOARG);
VOID CTYP _Two_OPEN(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
tmp=SIN;
_Sin_ENTRY();
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
tmp=PSIN;
_PSin_ENTRY();
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
tmp=MEANDR;
_Meandr_ENTRY();
return;
}

LCL VOID CTYP _opt4_ACT(NOARG)
{
tmp=ONE;
_One_ENTRY();
return;
}

LCL VOID CTYP _opt5_ACT(NOARG)
{
tmp=VOLUME;
_Two_ENTRY();
return;
}

LCL IbldT _MAIN_Itm[]={
{" Синусоидальный    ",'',ITM_NOR,0,0,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{" Полигармонический ",'',ITM_NOR,1,0,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{" Меандр            ",'',ITM_NOR,2,0,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   "",NULL},
{" Одиночный импульс ",'',ITM_NOR,3,0,  7,HLP_NONE,
   0,8,NULL,_opt4_ACT,NULL,
   "",NULL},
{" Одиночный уровень ",'',ITM_NOR,4,0,  9,HLP_NONE,
   0,10,NULL,_opt5_ACT,NULL,
   "",NULL},
{" Белый шум         ",'',ITM_NOR|ITM_NSL,5,0,  11,HLP_NONE,
   0,12,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,6,5,42,12,62,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_LGREY|BLACK,
   0,_MAIN_MSG,13, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Вх. сигнал├",BRD_TOP,4,_BLUE|INTENSE|LGREY);
  {
  extern MbldT _MAIN_Mnu;
  MnuDsp(&_MAIN_Mnu);
  }
  return;
}
LCL VOID CTYP _init_EXEC(NOARG)
{
// курсор на текущий тип генератора               
MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[UseGen]);  
                                                  
  return;
}

LCL ChrT Sin_var3[11];
LCL ChrT Sin_var5[16];
LCL ChrT Sin_var12[7];
LCL ChrT Sin_var16[11];
LCL FbldT _Sin_Fld[]={
 {"",0,0, Sin_var3,0,21,
  "999999.999",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, Sin_var5,1,16,
  "99999999.999999",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, Sin_var12,2,25,
  "999.99",NULL,NULL,NULL,
  0,16,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, Sin_var16,3,21,
  "999999.999",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _Sin_Frm={
 _Sin_Fld,4,NULL,NULL,18,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _Sin_OPEN(NOARG)
{

 Wopen(10,9,15,52,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Синусоида├",BRD_TOP,16,_BLUE|LGREY);
  Wprts(0,1,_BLUE|LGREY,"Амплитуда");
  Wprts(0,33,_BLUE|LGREY,"усл.ед.");
  Wprts(1,1,_BLUE|LGREY,"Частота");
  Wprts(1,33,_BLUE|LGREY,"Гц");
  Wprts(2,1,_BLUE|LGREY,"Фаза");
  Wprts(2,33,_BLUE|LGREY,"Рад");
  Wprts(3,1,_BLUE|LGREY,"Пост.состовляющая");
  Wprts(3,33,_BLUE|LGREY,"усл.ед.");

  _Sin_2STR();
  EntPush();
  EntBuild(&_Sin_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _Sin_2STR(NOARG)
{
  cvtfc(Sin_var3,GenBuf[SIN].U.Sin.Ampl,10,3);
  cvtfc(Sin_var5,GenBuf[SIN].U.Sin.Chast,15,6);
  cvtfc(Sin_var12,GenBuf[SIN].U.Sin.Faza,6,2);
  cvtfc(Sin_var16,GenBuf[SIN].U.Sin.Const,10,3);
 return;
}
LCL VOID CTYP _Sin_2VAL(NOARG)
{
    GenBuf[SIN].U.Sin.Ampl=cvtcf(Sin_var3);
    GenBuf[SIN].U.Sin.Chast=cvtcf(Sin_var5);
    GenBuf[SIN].U.Sin.Faza=cvtcf(Sin_var12);
    GenBuf[SIN].U.Sin.Const=cvtcf(Sin_var16);
 return;
}

LCL VOID CTYP _Sin_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _Sin_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _Sin_2STR();
 EntPush();
 EntBuild(&_Sin_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_Sin_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _Sin_2VAL();
    EntResult=1;
    }
  _set_EXEC();
}

LCL ChrT PSin_var1[11];
LCL ChrT PSin_var2[16];
LCL ChrT PSin_var4[7];
LCL ChrT PSin_var11[11];
LCL ChrT PSin_var14[16];
LCL ChrT PSin_var17[7];
LCL ChrT PSin_var18[11];
LCL ChrT PSin_var19[16];
LCL ChrT PSin_var20[7];
LCL ChrT PSin_var21[11];
LCL FbldT _PSin_Fld[]={
 {"",0,0, PSin_var1,1,21,
  "999999.999",NULL,NULL,NULL,
  0,19,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var2,2,16,
  "99999999.999999",NULL,NULL,NULL,
  0,20,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var4,3,25,
  "999.99",NULL,NULL,NULL,
  0,21,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var11,5,21,
  "999999.999",NULL,NULL,NULL,
  0,22,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var14,6,16,
  "99999999.999999",NULL,NULL,NULL,
  0,23,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var17,7,25,
  "999.99",NULL,NULL,NULL,
  0,24,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var18,9,21,
  "999999.999",NULL,NULL,NULL,
  0,25,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var19,10,16,
  "99999999.999999",NULL,NULL,NULL,
  0,26,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var20,11,25,
  "999.99",NULL,NULL,NULL,
  0,27,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, PSin_var21,12,21,
  "999999.999",NULL,NULL,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _PSin_Frm={
 _PSin_Fld,10,NULL,NULL,29,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _PSin_OPEN(NOARG)
{

 Wopen(7,11,21,54,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Полигармоника├",BRD_TOP,14,_BLUE|LGREY);
  Wprts(0,1,_BLUE|LGREY,"─");
  Wprts(0,3,_BLUE|INTENSE|LGREY,"Первая гармоника");
  Wprts(0,20,_BLUE|LGREY,"────────────────────");
  Wprts(1,1,_BLUE|LGREY,"Амплитуда");
  Wprts(1,33,_BLUE|LGREY,"усл.ед.");
  Wprts(2,1,_BLUE|LGREY,"Частота");
  Wprts(2,33,_BLUE|LGREY,"Гц");
  Wprts(3,1,_BLUE|LGREY,"Фаза");
  Wprts(3,33,_BLUE|LGREY,"Рад");
  Wprts(4,1,_BLUE|LGREY,"─");
  Wprts(4,3,_BLUE|INTENSE|LGREY,"Вторая гармоника ");
  Wprts(4,20,_BLUE|LGREY,"────────────────────");
  Wprts(5,1,_BLUE|LGREY,"Амплитуда");
  Wprts(5,33,_BLUE|LGREY,"усл.ед.");
  Wprts(6,1,_BLUE|LGREY,"Частота");
  Wprts(6,33,_BLUE|LGREY,"Гц");
  Wprts(7,1,_BLUE|LGREY,"Фаза");
  Wprts(7,33,_BLUE|LGREY,"Рад");
  Wprts(8,1,_BLUE|LGREY,"─");
  Wprts(8,3,_BLUE|INTENSE|LGREY,"Третья гармоника");
  Wprts(8,20,_BLUE|LGREY,"────────────────────");
  Wprts(9,1,_BLUE|LGREY,"Амплитуда");
  Wprts(9,33,_BLUE|LGREY,"усл.ед.");
  Wprts(10,1,_BLUE|LGREY,"Частота");
  Wprts(10,33,_BLUE|LGREY,"Гц");
  Wprts(11,1,_BLUE|LGREY,"Фаза");
  Wprts(11,33,_BLUE|LGREY,"Рад");
  Wprts(12,1,_BLUE|LGREY,"Пост.состовляющая");
  Wprts(12,33,_BLUE|LGREY,"усл.ед.");

  _PSin_2STR();
  EntPush();
  EntBuild(&_PSin_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _PSin_2STR(NOARG)
{
  cvtfc(PSin_var1,GenBuf[PSIN].U.PSin.Ampl[0],10,3);
  cvtfc(PSin_var2,GenBuf[PSIN].U.PSin.Chast[0],15,6);
  cvtfc(PSin_var4,GenBuf[PSIN].U.PSin.Faza[0],6,2);
  cvtfc(PSin_var11,GenBuf[PSIN].U.PSin.Ampl[1],10,3);
  cvtfc(PSin_var14,GenBuf[PSIN].U.PSin.Chast[1],15,6);
  cvtfc(PSin_var17,GenBuf[PSIN].U.PSin.Faza[1],6,2);
  cvtfc(PSin_var18,GenBuf[PSIN].U.PSin.Ampl[2],10,3);
  cvtfc(PSin_var19,GenBuf[PSIN].U.PSin.Chast[2],15,6);
  cvtfc(PSin_var20,GenBuf[PSIN].U.PSin.Faza[2],6,2);
  cvtfc(PSin_var21,GenBuf[PSIN].U.PSin.Const,10,3);
 return;
}
LCL VOID CTYP _PSin_2VAL(NOARG)
{
    GenBuf[PSIN].U.PSin.Ampl[0]=cvtcf(PSin_var1);
    GenBuf[PSIN].U.PSin.Chast[0]=cvtcf(PSin_var2);
    GenBuf[PSIN].U.PSin.Faza[0]=cvtcf(PSin_var4);
    GenBuf[PSIN].U.PSin.Ampl[1]=cvtcf(PSin_var11);
    GenBuf[PSIN].U.PSin.Chast[1]=cvtcf(PSin_var14);
    GenBuf[PSIN].U.PSin.Faza[1]=cvtcf(PSin_var17);
    GenBuf[PSIN].U.PSin.Ampl[2]=cvtcf(PSin_var18);
    GenBuf[PSIN].U.PSin.Chast[2]=cvtcf(PSin_var19);
    GenBuf[PSIN].U.PSin.Faza[2]=cvtcf(PSin_var20);
    GenBuf[PSIN].U.PSin.Const=cvtcf(PSin_var21);
 return;
}

LCL VOID CTYP _PSin_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _PSin_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _PSin_2STR();
 EntPush();
 EntBuild(&_PSin_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_PSin_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _PSin_2VAL();
    EntResult=1;
    }
  _set_EXEC();
}

LCL ChrT Meandr_var6[11];
LCL ChrT Meandr_var8[16];
LCL ChrT Meandr_var15[11];
LCL FbldT _Meandr_Fld[]={
 {"",0,0, Meandr_var6,0,21,
  "999999.999",NULL,NULL,NULL,
  0,30,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, Meandr_var8,1,16,
  "99999999.999999",NULL,NULL,NULL,
  0,31,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, Meandr_var15,2,21,
  "999999.999",NULL,NULL,NULL,
  0,32,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _Meandr_Frm={
 _Meandr_Fld,3,NULL,NULL,33,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _Meandr_OPEN(NOARG)
{

 Wopen(11,8,15,51,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Меандр├",BRD_TOP,16,_BLUE|LGREY);
  Wprts(0,1,_BLUE|LGREY,"Амплитуда");
  Wprts(0,33,_BLUE|LGREY,"усл.ед.");
  Wprts(1,1,_BLUE|LGREY,"Частота");
  Wprts(1,33,_BLUE|LGREY,"Гц");
  Wprts(2,1,_BLUE|LGREY,"Пост.состовляющая");
  Wprts(2,33,_BLUE|LGREY,"усл.ед.");

  _Meandr_2STR();
  EntPush();
  EntBuild(&_Meandr_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _Meandr_2STR(NOARG)
{
  cvtfc(Meandr_var6,GenBuf[MEANDR].U.Meandr.Ampl,10,3);
  cvtfc(Meandr_var8,GenBuf[MEANDR].U.Meandr.Chast,15,6);
  cvtfc(Meandr_var15,GenBuf[MEANDR].U.Meandr.Const,10,3);
 return;
}
LCL VOID CTYP _Meandr_2VAL(NOARG)
{
    GenBuf[MEANDR].U.Meandr.Ampl=cvtcf(Meandr_var6);
    GenBuf[MEANDR].U.Meandr.Chast=cvtcf(Meandr_var8);
    GenBuf[MEANDR].U.Meandr.Const=cvtcf(Meandr_var15);
 return;
}

LCL VOID CTYP _Meandr_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _Meandr_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _Meandr_2STR();
 EntPush();
 EntBuild(&_Meandr_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_Meandr_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _Meandr_2VAL();
    EntResult=1;
    }
}

LCL ChrT One_var7[11];
LCL ChrT One_var9[16];
LCL FbldT _One_Fld[]={
 {"",0,0, One_var7,0,23,
  "999999.999",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, One_var9,1,18,
  "99999999.999999",NULL,NULL,NULL,
  0,35,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _One_Frm={
 _One_Fld,2,NULL,NULL,36,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _One_OPEN(NOARG)
{

 Wopen(11,8,14,51,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Одиночный импульс├",BRD_TOP,13,_BLUE|LGREY);
  Wprts(0,1,_BLUE|LGREY,"Амплитуда");
  Wprts(0,34,_BLUE|LGREY,"усл.ед.");
  Wprts(1,1,_BLUE|LGREY,"Задержка");
  Wprts(1,10,_BLUE|LGREY,"начала");
  Wprts(1,34,_BLUE|LGREY,"мс.");

  _One_2STR();
  EntPush();
  EntBuild(&_One_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _One_2STR(NOARG)
{
  cvtfc(One_var7,GenBuf[ONE].U.One.Ampl,10,3);
  cvtfc(One_var9,GenBuf[ONE].U.One.Wait,15,6);
 return;
}
LCL VOID CTYP _One_2VAL(NOARG)
{
    GenBuf[ONE].U.One.Ampl=cvtcf(One_var7);
    GenBuf[ONE].U.One.Wait=cvtcf(One_var9);
 return;
}

LCL VOID CTYP _One_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _One_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _One_2STR();
 EntPush();
 EntBuild(&_One_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_One_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _One_2VAL();
    EntResult=1;
    }
  _set_EXEC();
}

LCL ChrT Two_var10[11];
LCL ChrT Two_var13[16];
LCL FbldT _Two_Fld[]={
 {"",0,0, Two_var10,0,23,
  "999999.999",NULL,NULL,NULL,
  0,37,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, Two_var13,1,18,
  "99999999.999999",NULL,NULL,NULL,
  0,38,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _Two_Frm={
 _Two_Fld,2,NULL,NULL,39,0,
 0,_BLUE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _Two_OPEN(NOARG)
{

 Wopen(12,8,15,51,BOX_VER,
       _BLUE|LGREY,_BLUE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Одиночный уровень├",BRD_TOP,13,_BLUE|LGREY);
  Wprts(0,1,_BLUE|LGREY,"Амплитуда");
  Wprts(0,34,_BLUE|LGREY,"усл.ед.");
  Wprts(1,1,_BLUE|LGREY,"Задержка");
  Wprts(1,10,_BLUE|LGREY,"начала");
  Wprts(1,34,_BLUE|LGREY,"мс.");

  _Two_2STR();
  EntPush();
  EntBuild(&_Two_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _Two_2STR(NOARG)
{
  cvtfc(Two_var10,GenBuf[VOLUME].U.Volume.Ampl,10,3);
  cvtfc(Two_var13,GenBuf[VOLUME].U.Volume.Wait,15,6);
 return;
}
LCL VOID CTYP _Two_2VAL(NOARG)
{
    GenBuf[VOLUME].U.Volume.Ampl=cvtcf(Two_var10);
    GenBuf[VOLUME].U.Volume.Wait=cvtcf(Two_var13);
 return;
}

LCL VOID CTYP _Two_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _Two_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _Two_2STR();
 EntPush();
 EntBuild(&_Two_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_Two_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _Two_2VAL();
    EntResult=1;
    }
  _set_EXEC();
}
LCL VOID CTYP _set_EXEC(NOARG)
{
 if(EntResult==1) UseGen=tmp;                
                                             
  return;
}
VOID CTYP MOD_TEST(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[0]);
  _init_EXEC();
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_MAIN_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
