

/*
 *   Generated by  UI v2.00 
 *        December 24, 1993
 */


/* Module: MENU\NEW_GD.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _main_2STR(NOARG);

VOID CTYP NEW_GD(NOARG)
{
 Wopen(6,21,18,57,BOX_DBL,
       _BLUE|LGREY,_BLUE|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
 MouPush(MOU_FULL);
 CurHide();
 KeyWait();
 CurShow();
 MouPop();
 Wclose();
  return;
}

/*** END OF FILE ***/
