

/*
 *   Generated by  UI v2.00 
 *        June 25, 1993
 */


/* Module: MENU\SAVE_YN.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "dsys.h"
#include "menu.h"


VOID CTYP _MAIN_2STR(NOARG);
VOID CTYP _MAIN_MSG(NOARG);


LCL VOID CTYP _opt1_ACT(NOARG)
{
trigger=SAVE;
return;
}

LCL VOID CTYP _opt2_ACT(NOARG)
{
trigger=CONTINUE;
return;
}

LCL VOID CTYP _opt3_ACT(NOARG)
{
trigger=CANCEL;
return;
}

LCL IbldT _MAIN_Itm[]={
{"  Сохранить ",'',ITM_NOR|ITM_BEF,1,1,  1,HLP_NONE,
   0,2,NULL,_opt1_ACT,NULL,
   "",NULL},
{"Не сохранять",'',ITM_NOR|ITM_BEF,1,15,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{"  Прервать  ",'',ITM_NOR|ITM_BEF,1,29,  5,HLP_NONE,
   0,6,NULL,_opt3_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _MAIN_MSG(NOARG);
LCL MbldT _MAIN_Mnu={
   _MAIN_Itm,3,6,18,10,61,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_VER,
   _BROWN|INTENSE|LGREY,_BROWN|INTENSE|LGREY,_BROWN|INTENSE|LGREY,
   _BROWN|BLACK,_BROWN|BLACK,_LGREY|BLACK,
   0,_MAIN_MSG,7, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _MAIN_MSG(NOARG)
{

 Wshadow(_BLACK|DGREY);
 CurHide();
  Wmessage("┤Схема не сохранена├",BRD_TOP,12,_BROWN|INTENSE|LGREY);
  {
  MnuDsp(&_MAIN_Mnu);
  }
  return;
}
VOID CTYP SAVE_YN(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_MAIN_Mnu)=IbldTag(&_MAIN_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_MAIN_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
