

/*
 *   Generated by  UI v2.00 
 *        December 2, 1993
 */


/* Module: MENU\ZVENO_Z.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#include "dsys.h"
#include "menu.h"
#define par ParBuf
extern ParamT ParBuf;

VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_OPEN(NOARG);


LCL ChrT main_var1[12];
LCL ChrT main_var2[12];
LCL ChrT main_var3[12];
LCL ChrT main_var4[12];
LCL ChrT main_var5[12];
LCL ChrT main_var6[12];
LCL FbldT _main_Fld[]={
 {"",0,0, main_var1,2,12,
  "9999.999999",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var2,2,27,
  "9999.999999",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var3,2,44,
  "9999.999999",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var4,5,12,
  "9999.999999",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var5,5,27,
  "9999.999999",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_var6,5,44,
  "9999.999999",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_Frm={
 _main_Fld,6,NULL,NULL,7,0,
 0,_BLUE|INTENSE|LGREY,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _main_OPEN(NOARG)
{

 Wopen(7,5,16,68,BOX_DBL,
       _BLUE|LGREY,_BLUE|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wbprintc(BRD_TOP,22,_BLUE|LGREY,'╡');
  Wmessage("Динамическое звено",BRD_TOP,23,_BLUE|INTENSE|LGREY);
  Wbprintc(BRD_TOP,41,_BLUE|LGREY,'╞');
  Wprts(1,40,_BLUE|LGREY," ");
  Wprts(1,56,_BLUE|LGREY," 2 ");
  Wprts(2,24,_BLUE|LGREY,"+");
  Wprts(2,39,_BLUE|LGREY,"P  +");
  Wprts(2,56,_BLUE|LGREY,"P");
  Wprts(3,1,_BLUE|LGREY,"W(Z) =  ─────────────────────────────────────────────────── ");
  Wprts(4,38,_BLUE|LGREY,"                   2  ");
  Wprts(5,19,_BLUE|LGREY,"     + ");
  Wprts(5,38,_BLUE|LGREY," P  +");
  Wprts(5,55,_BLUE|LGREY," P  ");

  _main_2STR();
  EntPush();
  EntBuild(&_main_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _main_2STR(NOARG)
{
  cvtfc(main_var1,par.U.EasyZveno.A0,11,6);
  cvtfc(main_var2,par.U.EasyZveno.A1,11,6);
  cvtfc(main_var3,par.U.EasyZveno.A2,11,6);
  cvtfc(main_var4,par.U.EasyZveno.B0,11,6);
  cvtfc(main_var5,par.U.EasyZveno.B1,11,6);
  cvtfc(main_var6,par.U.EasyZveno.B2,11,6);
 return;
}
LCL VOID CTYP _main_2VAL(NOARG)
{
    par.U.EasyZveno.A0=cvtcf(main_var1);
    par.U.EasyZveno.A1=cvtcf(main_var2);
    par.U.EasyZveno.A2=cvtcf(main_var3);
    par.U.EasyZveno.B0=cvtcf(main_var4);
    par.U.EasyZveno.B1=cvtcf(main_var5);
    par.U.EasyZveno.B2=cvtcf(main_var6);
 return;
}

VOID CTYP ZVENO_Z(NOARG)
{
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _main_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _main_2STR();
 EntPush();
 EntBuild(&_main_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _main_2VAL();
    EntResult=1;
    }
}
  return;
}

/*** END OF FILE ***/
